// Emits Verilog and VHDL for an expression, so a design worked out here can be
// pasted into a simulator or onto an FPGA without being retyped.
//
// Both outputs are single combinational assignments over the same AST the rest
// of the site uses, which keeps them honest: the test suite parses the emitted
// operators back and checks the truth table still matches.

import { variablesOf, type Ast } from './boolean.js';

export type Hdl = 'verilog' | 'vhdl';

// Signal names need no escaping here: the parser splits a run of letters into
// single letter variables, and neither language reserves a one letter word.

/**
 * Renders the expression itself. Both languages get full brackets rather than
 * relying on precedence: VHDL does not even define a precedence between AND and
 * OR, so `a and b or c` is a syntax error there, and being explicit means one
 * code path can serve both.
 */
function expression(ast: Ast, target: Hdl): string {
	const ops =
		target === 'verilog'
			? { and: ' & ', or: ' | ', xor: ' ^ ', not: (v: string) => `~${v}` }
			: { and: ' and ', or: ' or ', xor: ' xor ', not: (v: string) => `not ${v}` };

	const walk = (n: Ast, top: boolean): string => {
		switch (n.t) {
			case 'var':
				return n.name;
			case 'const':
				return target === 'verilog' ? (n.v ? "1'b1" : "1'b0") : n.v ? "'1'" : "'0'";
			case 'not':
				// walk already brackets anything that is not a leaf.
				return ops.not(walk(n.a, false));
			default: {
				const body = `${walk(n.a, false)}${ops[n.t]}${walk(n.b, false)}`;
				return top ? body : `(${body})`;
			}
		}
	};
	return walk(ast, true);
}

/** A whole compilable unit: entity or module, ports, and the one assignment. */
export function toHdl(ast: Ast, target: Hdl, name = 'logic_nodes'): string {
	const inputs = variablesOf(ast);
	const body = expression(ast, target);

	if (target === 'verilog') {
		return [
			`// Generated by nodes.kriyak.com`,
			`module ${name} (`,
			...inputs.map((v) => `    input  wire ${v},`),
			`    output wire y`,
			`);`,
			``,
			`    assign y = ${body};`,
			``,
			`endmodule`
		].join('\n');
	}

	return [
		`-- Generated by nodes.kriyak.com`,
		`library ieee;`,
		`use ieee.std_logic_1164.all;`,
		``,
		`entity ${name} is`,
		`    port (`,
		...inputs.map((v) => `        ${v} : in  std_logic;`),
		`        y : out std_logic`,
		`    );`,
		`end entity;`,
		``,
		`architecture rtl of ${name} is`,
		`begin`,
		``,
		`    y <= ${body};`,
		``,
		`end architecture;`
	].join('\n');
}

/**
 * The expression on its own, without the surrounding module. This is what you
 * want when pasting into a design that already has its ports declared.
 */
export function toHdlExpression(ast: Ast, target: Hdl): string {
	return expression(ast, target);
}

export const hdlTargets: { id: Hdl; label: string; extension: string }[] = [
	{ id: 'verilog', label: 'Verilog', extension: 'v' },
	{ id: 'vhdl', label: 'VHDL', extension: 'vhd' }
];
