// The QR encoder against known answers and the standard's capacity and
// format tables, whole symbols against an independent encoder (python-qrcode),
// Reed–Solomon codewords checked by syndromes computed with an independent
// field multiply, the BCH codes checked by polynomial division, and the layout
// of the function patterns. Then the page, as a reader uses it.
//
// During development every version, level, mode and mask was also rendered and
// read back with OpenCV's QR decoder; that needs Python, so it is not part of
// this suite.

import { createHash } from 'node:crypto';
import { expect, test } from '@playwright/test';
import {
	encodeQr,
	capacity,
	dataCodewords,
	totalCodewords,
	remainderBits,
	rawDataModules,
	blockLayout,
	alignmentPositions,
	charCountBits,
	chooseMode,
	smallestVersion,
	formatBits,
	versionBits,
	FORMAT_MASK,
	FORMAT_GENERATOR,
	VERSION_GENERATOR,
	GF_EXP,
	gfMul,
	rsRemainder,
	penalty,
	MASKS,
	EC_LEVELS,
	symbolSize,
	codewordOutlines,
	codewordLabels,
	rolePaths,
	qrSvg,
	describeModule,
	finderBaseline,
	QrError,
	type QrCode,
	type EcLevel
} from '../src/lib/qr.js';

/** Carry-less multiply then reduce by 0x11D, bit by bit: a different route to the same field. */
function slowMul(a: number, b: number): number {
	let product = 0;
	for (let i = 0; i < 8; i++) if ((b >> i) & 1) product ^= a << i;
	for (let bit = 15; bit >= 8; bit--) if ((product >> bit) & 1) product ^= 0x11d << (bit - 8);
	return product;
}

function slowPow(a: number, n: number): number {
	let r = 1;
	for (let i = 0; i < n; i++) r = slowMul(r, a);
	return r;
}

/** The remainder of a binary polynomial division, for the BCH checks. */
function polyMod(value: number, generator: number): number {
	const gLen = generator.toString(2).length;
	for (let bit = value.toString(2).length - 1; bit >= gLen - 1; bit--)
		if ((value >> bit) & 1) value ^= generator << (bit - gLen + 1);
	return value;
}

const popcount = (n: number) => n.toString(2).replace(/0/g, '').length;

/** A deterministic random generator, so a failure can be reproduced. */
function rng(seed: number) {
	return () => {
		seed = (seed * 1103515245 + 12345) & 0x7fffffff;
		return seed / 0x80000000;
	};
}

const errorOf = (fn: () => unknown): string => {
	try {
		fn();
	} catch (e) {
		expect(e).toBeInstanceOf(QrError);
		return (e as Error).message;
	}
	throw new Error('expected a QrError');
};

/** The 15 format bits as read back from one of the two copies in a symbol. */
function readFormat(qr: QrCode, copy: 1 | 2): number {
	let bits = 0;
	for (let y = 0; y < qr.size; y++)
		for (let x = 0; x < qr.size; x++) {
			const m = qr.info[y][x];
			if (m.role === 'format' && m.copy === copy && qr.modules[y][x]) bits |= 1 << m.bit;
		}
	return bits;
}

test.describe('known answers', () => {
	test('HELLO WORLD at 1-Q, codewords and error correction', () => {
		const qr = encodeQr('HELLO WORLD', { ec: 'Q' });
		expect(qr).toMatchObject({ version: 1, size: 21, mode: 'alphanumeric', count: 11 });
		expect(qr.fields[0].bits).toBe('0010');
		expect(qr.fields[1].bits).toBe('000001011');
		expect(qr.groups.slice(0, 2)).toEqual([
			{ chars: 'HE', value: 779, bits: '01100001011' },
			{ chars: 'LL', value: 966, bits: '01111000110' }
		]);
		expect(qr.groups[5]).toEqual({ chars: 'D', value: 13, bits: '001101' });
		expect(qr.dataCodewords).toEqual([32, 91, 11, 120, 209, 114, 220, 77, 67, 64, 236, 17, 236]);
		expect(qr.blocks).toHaveLength(1);
		expect(qr.blocks[0].ec).toEqual([168, 72, 22, 82, 217, 54, 156, 0, 46, 15, 180, 122, 16]);
		expect(qr.sequence).toEqual([...qr.dataCodewords, ...qr.blocks[0].ec]);
		expect(qr.padCount).toBe(3);
	});

	test('01234567, the numeric mode example', () => {
		const qr = encodeQr('01234567', { ec: 'M' });
		const bits = qr.fields
			.slice(0, 3)
			.map((f) => f.bits)
			.join('');
		expect(bits).toBe('0001' + '0000001000' + '0000001100' + '0101011001' + '1000011');
		expect(qr.dataCodewords).toEqual([
			0x10, 0x20, 0x0c, 0x56, 0x61, 0x80, 0xec, 0x11, 0xec, 0x11, 0xec, 0x11, 0xec, 0x11, 0xec, 0x11
		]);
		expect(qr.blocks[0].ec).toEqual([0xa5, 0x24, 0xd4, 0xc1, 0xed, 0x36, 0xc7, 0x87, 0x2c, 0x55]);
	});
});

/** The finished symbol as rows of 0 and 1, one line per row. */
const rowsOf = (qr: QrCode) => qr.modules.map((row) => row.map((d) => (d ? '1' : '0')).join(''));

test.describe('whole symbols', () => {
	// HELLO WORLD at 1-Q with mask 2, module for module. Generated by
	// python-qrcode 7.4.2 and segno 1.6.6, which agree, and read back by OpenCV.
	test('HELLO WORLD 1-Q, mask 2, matches an independent encoder', () => {
		const expected = [
			'#######.#.#...#######',
			'#.....#.....#.#.....#',
			'#.###.#..####.#.###.#',
			'#.###.#....##.#.###.#',
			'#.###.#.##....#.###.#',
			'#.....#.#.###.#.....#',
			'#######.#.#.#.#######',
			'...........##........',
			'.#######.##.#..##...#',
			'#....#.####.##..#####',
			'....#####......#.#..#',
			'#.#.#.....#.#..#.....',
			'#.##..#..#.##.....#..',
			'........##..###..#.##',
			'#######.##....#.###.#',
			'#.....#.##...###..##.',
			'#.###.#.##.......###.',
			'#.###.#.##..#..#.##..',
			'#.###.#.####.#..##...',
			'#.....#.#.#.......#.#',
			'#######..###.#..#....'
		].map((row) => row.replace(/#/g, '1').replace(/\./g, '0'));
		expect(rowsOf(encodeQr('HELLO WORLD', { ec: 'Q', mask: 2 }))).toEqual(expected);
	});

	// SHA-256 of the rows (joined by newlines) that python-qrcode 7.4.2 draws for
	// the same text, level, version and mask. Every mask, a version information
	// block (7, 8, 27, 40), byte mode in UTF-8, and the largest symbol.
	test('symbols of every mask and several versions match python-qrcode', () => {
		const known: [string, EcLevel, number, number, string][] = [
			['HELLO WORLD', 'Q', 1, 0, '7cb519f187a1f6d6294385b11fd9d65487509b897a600c9c5e6398297cd45222'],
			['HELLO WORLD', 'Q', 1, 1, '9e1a2e4bb77f9908f8150a42cf275dfa0a9381ba05fe4b4ef3878253ce7ad5c7'],
			['HELLO WORLD', 'Q', 1, 2, '724951d69bf5dfb47a3b67472a069262477ff6d3dea7f8839f918115bf278191'],
			['HELLO WORLD', 'Q', 1, 3, '063cdfe169ae8d951fc95c2f178693c23bc4d4a985c3bc7700ba9fdd2c236804'],
			['HELLO WORLD', 'Q', 1, 4, '36249750eb97d183f0c539768ef08ffe75a21bd68d6a731ad238055fb2905254'],
			['HELLO WORLD', 'Q', 1, 5, 'ca4241df38353e650ce4ca991f74af44b46ecb20f08b2423382653bdf1f2325e'],
			['HELLO WORLD', 'Q', 1, 6, '453d0cc77a27d60d29801fcff544b4230f4e83183ac83d8ea4836c75c67f2ae5'],
			['HELLO WORLD', 'Q', 1, 7, '7dbbd96a111220738c00f0db3922aa9a59f0ed2d3df202b75ea915af98e2995a'],
			['01234567', 'M', 1, 0, '88ee0d88685d91c62d8eab6cbb409036311d26c9a63fc423058b4d4a4d651ebb'],
			[
				'https://logicgates.org/qr-code-generator',
				'H',
				7,
				5,
				'142be3f26cb316fe07ccb74d3cf1b431f4e42e2c21884c1067de3f2d09dc1f88'
			],
			['VERSION INFORMATION', 'L', 8, 3, '17966ee5b0f1f18f1055b22882200471d330adff55f869e852d463f6d851d645'],
			['café ☕', 'L', 1, 6, '7390221255da35e56c8f9fa41beef0e17eea158ca4951cf77bb3b083a2527285'],
			[
				'31415926535897932384626433832795028841971693993751',
				'Q',
				27,
				4,
				'4671c33f287e0df7c758a69f46e1f79384ec44aeff0e6075b2dc2ba4b11ad04a'
			],
			['Version forty', 'M', 40, 7, 'c70db03d28430aad64bf98e08062caf7916dc8370ab6f3539372ae45c5997141']
		];
		for (const [text, ec, version, mask, hash] of known) {
			const rows = rowsOf(encodeQr(text, { ec, version, mask }));
			expect(createHash('sha256').update(rows.join('\n')).digest('hex'), `${text} ${version}-${ec} mask ${mask}`).toBe(
				hash
			);
		}
	});

	test('the mask formulas, written out as the standard has them (i is the row, j the column)', () => {
		const standard: ((i: number, j: number) => boolean)[] = [
			(i, j) => (i + j) % 2 === 0,
			(i) => i % 2 === 0,
			(i, j) => j % 3 === 0,
			(i, j) => (i + j) % 3 === 0,
			(i, j) => (Math.floor(i / 2) + Math.floor(j / 3)) % 2 === 0,
			(i, j) => ((i * j) % 2) + ((i * j) % 3) === 0,
			(i, j) => (((i * j) % 2) + ((i * j) % 3)) % 2 === 0,
			(i, j) => (((i * j) % 3) + ((i + j) % 2)) % 2 === 0
		];
		for (let k = 0; k < 8; k++)
			for (let i = 0; i < 30; i++)
				for (let j = 0; j < 30; j++)
					expect(MASKS[k].test(j, i), `mask ${k} at row ${i}, column ${j}`).toBe(standard[k](i, j));
	});

	test('format and version modules sit at the standard coordinates', () => {
		const qr = encodeQr('FORMAT', { ec: 'M', version: 1 });
		// "column,row" of format bits 0 to 14 (bit 0 the least significant), per copy.
		const copies = [
			'8,0 8,1 8,2 8,3 8,4 8,5 8,7 8,8 7,8 5,8 4,8 3,8 2,8 1,8 0,8',
			'20,8 19,8 18,8 17,8 16,8 15,8 14,8 13,8 8,14 8,15 8,16 8,17 8,18 8,19 8,20'
		];
		for (const [c, list] of copies.entries())
			for (const [bit, xy] of list.split(' ').entries()) {
				const [x, y] = xy.split(',').map(Number);
				expect(qr.info[y][x], `format copy ${c + 1} bit ${bit}`).toMatchObject({ role: 'format', bit, copy: c + 1 });
				expect(qr.modules[y][x]).toBe(((qr.formatBits >> bit) & 1) === 1);
			}
		// Version 7 is 45 modules. Version bits 0 to 17 in the upper right block, as
		// "column,row"; the lower left block is its transpose.
		const big = encodeQr('V', { version: 7, ec: 'L' });
		const bits = 0b000111110010010100;
		const upper = '34,0 35,0 36,0 34,1 35,1 36,1 34,2 35,2 36,2 34,3 35,3 36,3 34,4 35,4 36,4 34,5 35,5 36,5'.split(
			' '
		);
		for (const [bit, xy] of upper.entries()) {
			const [x, y] = xy.split(',').map(Number);
			const dark = ((bits >> bit) & 1) === 1;
			expect(big.info[y][x]).toMatchObject({ role: 'version', bit, copy: 1 });
			expect(big.info[x][y]).toMatchObject({ role: 'version', bit, copy: 2 });
			expect([big.modules[y][x], big.modules[x][y]]).toEqual([dark, dark]);
		}
	});
});

test.describe('capacity tables', () => {
	test('characters per symbol match the standard', () => {
		const table: [number, EcLevel, number, number, number][] = [
			[1, 'L', 41, 25, 17],
			[1, 'M', 34, 20, 14],
			[1, 'Q', 27, 16, 11],
			[1, 'H', 17, 10, 7],
			[10, 'L', 652, 395, 271],
			[10, 'M', 513, 311, 213],
			[10, 'Q', 364, 221, 151],
			[10, 'H', 288, 174, 119],
			[40, 'L', 7089, 4296, 2953],
			[40, 'M', 5596, 3391, 2331],
			[40, 'Q', 3993, 2420, 1663],
			[40, 'H', 3057, 1852, 1273]
		];
		for (const [v, ec, numeric, alnum, bytes] of table) {
			expect([capacity(v, ec, 'numeric'), capacity(v, ec, 'alphanumeric'), capacity(v, ec, 'byte')]).toEqual([
				numeric,
				alnum,
				bytes
			]);
		}
	});

	test('codeword counts, blocks and remainder bits', () => {
		expect(EC_LEVELS.map((ec) => dataCodewords(1, ec))).toEqual([19, 16, 13, 9]);
		expect(EC_LEVELS.map((ec) => dataCodewords(40, ec))).toEqual([2956, 2334, 1666, 1276]);
		expect(totalCodewords(1)).toBe(26);
		expect(totalCodewords(40)).toBe(3706);
		expect(blockLayout(5, 'Q')).toEqual([
			{ count: 2, data: 15, ec: 18 },
			{ count: 2, data: 16, ec: 18 }
		]);
		expect(blockLayout(21, 'L')).toEqual([
			{ count: 4, data: 116, ec: 28 },
			{ count: 4, data: 117, ec: 28 }
		]);
		const remainders = Array.from({ length: 40 }, (_, i) => remainderBits(i + 1));
		const expected = (v: number) =>
			v === 1 ? 0 : v <= 6 ? 7 : v <= 13 ? 0 : v <= 20 ? 3 : v <= 27 ? 4 : v <= 34 ? 3 : 0;
		expect(remainders).toEqual(remainders.map((_, i) => expected(i + 1)));
		for (let v = 1; v <= 40; v++)
			for (const ec of EC_LEVELS) {
				const layout = blockLayout(v, ec);
				expect(layout.reduce((n, g) => n + g.count * (g.data + g.ec), 0)).toBe(totalCodewords(v));
			}
	});

	test('the character count field widens at versions 10 and 27', () => {
		expect([9, 10, 26, 27].map((v) => charCountBits('numeric', v))).toEqual([10, 12, 12, 14]);
		expect([9, 10, 26, 27].map((v) => charCountBits('alphanumeric', v))).toEqual([9, 11, 11, 13]);
		expect([9, 10, 26, 27].map((v) => charCountBits('byte', v))).toEqual([8, 16, 16, 16]);
	});

	test('a full symbol fits, one character more needs the next version', () => {
		for (const v of [1, 2, 9, 10, 26, 27, 39])
			for (const ec of EC_LEVELS) {
				const digits = '7'.repeat(capacity(v, ec, 'numeric'));
				expect(smallestVersion(digits, ec)).toBe(v);
				expect(smallestVersion(digits + '7', ec)).toBe(v + 1);
				const letters = 'A'.repeat(capacity(v, ec, 'alphanumeric'));
				expect(smallestVersion(letters, ec)).toBe(v);
				expect(smallestVersion(letters + 'A', ec)).toBe(v + 1);
				const bytes = 'a'.repeat(capacity(v, ec, 'byte'));
				expect(smallestVersion(bytes, ec)).toBe(v);
				expect(smallestVersion(bytes + 'a', ec)).toBe(v + 1);
			}
	});
});

test.describe('modes', () => {
	test('the most compact mode that fits the whole text', () => {
		expect(chooseMode('0123456789')).toBe('numeric');
		expect(chooseMode('HELLO WORLD')).toBe('alphanumeric');
		expect(chooseMode('HTTP://EXAMPLE.COM/A-B')).toBe('alphanumeric');
		expect(chooseMode('Hello')).toBe('byte');
		expect(chooseMode('ABC!')).toBe('byte');
		expect(chooseMode('café')).toBe('byte');
	});

	test('numeric groups of three, and byte mode as UTF-8', () => {
		const numeric = encodeQr('01234567', { ec: 'M' });
		expect(numeric.groups.map((g) => [g.chars, g.bits])).toEqual([
			['012', '0000001100'],
			['345', '0101011001'],
			['67', '1000011']
		]);
		const bytes = encodeQr('é😀', { ec: 'L' });
		expect(bytes.count).toBe(6);
		expect(bytes.groups.map((g) => g.value)).toEqual([0xc3, 0xa9, 0xf0, 0x9f, 0x98, 0x80]);
		expect(bytes.groups.map((g) => g.chars)).toEqual(['é', '', '😀', '', '', '']);
	});

	test('the bit stream: terminator, zeros to a byte, then alternating pad bytes', () => {
		for (const text of ['1', 'HELLO WORLD', 'Hello, world', 'x'.repeat(17)]) {
			const qr = encodeQr(text, { ec: 'L' });
			const bits = qr.fields.map((f) => f.bits).join('');
			expect(bits.length).toBe(dataCodewords(qr.version, 'L') * 8);
			const terminator = qr.fields.find((f) => f.kind === 'terminator');
			expect(terminator?.bits).toMatch(/^0{0,4}$/);
			const pads = qr.dataCodewords.slice(qr.dataCodewords.length - qr.padCount);
			expect(pads).toEqual(pads.map((_, i) => (i % 2 ? 0x11 : 0xec)));
		}
	});
});

test.describe('the field and the error correction', () => {
	test('the exponent table is the powers of α = 2', () => {
		for (let i = 0; i < 255; i++) expect(GF_EXP[i]).toBe(slowPow(2, i));
		expect(new Set(GF_EXP.slice(0, 255)).size).toBe(255);
		const random = rng(5);
		for (let n = 0; n < 2000; n++) {
			const a = Math.floor(random() * 256);
			const b = Math.floor(random() * 256);
			expect(gfMul(a, b)).toBe(slowMul(a, b));
		}
	});

	test('every block is a codeword: the syndromes at α⁰ … α^(n−1) are zero', () => {
		const random = rng(11);
		for (let n = 0; n < 60; n++) {
			const v = 1 + Math.floor(random() * 40);
			const ec = EC_LEVELS[Math.floor(random() * 4)];
			const text = 'Q'.repeat(1 + Math.floor(random() * capacity(v, ec, 'alphanumeric')));
			const qr = encodeQr(text, { ec, version: Math.max(v, smallestVersion(text, ec)) });
			const syndromes: number[] = [];
			for (const block of qr.blocks) {
				const word = [...block.data, ...block.ec];
				for (let i = 0; i < block.ec.length; i++) {
					const root = slowPow(2, i);
					let s = 0;
					for (const c of word) s = slowMul(s, root) ^ c;
					syndromes.push(s);
				}
			}
			expect(syndromes.filter((s) => s !== 0)).toEqual([]);
		}
		// A changed codeword is detected.
		const data = [1, 2, 3, 4, 5];
		const ecw = rsRemainder(data, 10);
		const word = [...data, ...ecw];
		word[2] ^= 0x40;
		let s = 0;
		for (const c of word) s = slowMul(s, 2) ^ c;
		expect(s).not.toBe(0);
	});

	test('blocks are interleaved: first codeword of each block, then the second, and so on', () => {
		const qr = encodeQr('x'.repeat(100), { ec: 'H' });
		expect(qr.blocks.length).toBeGreaterThan(1);
		const b = qr.blocks;
		expect(qr.sequence.slice(0, b.length)).toEqual(b.map((block) => block.data[0]));
		const dataTotal = b.reduce((n, block) => n + block.data.length, 0);
		expect(qr.sequence.slice(dataTotal, dataTotal + b.length)).toEqual(b.map((block) => block.ec[0]));
		expect(qr.sequence.length).toBe(totalCodewords(qr.version));
		expect(qr.origin.filter((o) => o.kind === 'data')).toHaveLength(dataTotal);
	});
});

test.describe('format and version information', () => {
	test('the format bits match the standard', () => {
		expect(formatBits('L', 0).toString(2).padStart(15, '0')).toBe('111011111000100');
		expect(formatBits('M', 0).toString(2).padStart(15, '0')).toBe('101010000010010');
		expect(formatBits('Q', 0).toString(2).padStart(15, '0')).toBe('011010101011111');
		expect(formatBits('H', 0).toString(2).padStart(15, '0')).toBe('001011010001001');
	});

	test('every format code is a BCH(15,5) codeword at distance 7 or more from the others', () => {
		const codes = EC_LEVELS.flatMap((ec) => MASKS.map((_, k) => formatBits(ec, k)));
		expect(new Set(codes).size).toBe(32);
		for (const c of codes) expect(polyMod(c ^ FORMAT_MASK, FORMAT_GENERATOR)).toBe(0);
		for (const a of codes) for (const b of codes) if (a !== b) expect(popcount(a ^ b)).toBeGreaterThanOrEqual(7);
	});

	test('the version bits match the standard, and are BCH(18,6) codewords', () => {
		expect(versionBits(7)).toBe(0x07c94);
		expect(versionBits(8)).toBe(0x085bc);
		expect(versionBits(40)).toBe(0x28c69);
		const codes = Array.from({ length: 34 }, (_, i) => versionBits(i + 7));
		for (const [i, c] of codes.entries()) {
			expect(c >> 12).toBe(i + 7);
			expect(polyMod(c, VERSION_GENERATOR)).toBe(0);
		}
		for (const a of codes) for (const b of codes) if (a !== b) expect(popcount(a ^ b)).toBeGreaterThanOrEqual(8);
	});

	test('both copies in the symbol agree, for every level and mask', () => {
		for (const ec of EC_LEVELS)
			for (let mask = 0; mask < 8; mask++) {
				const qr = encodeQr('FORMAT', { ec, mask });
				expect(readFormat(qr, 1)).toBe(formatBits(ec, mask));
				expect(readFormat(qr, 2)).toBe(formatBits(ec, mask));
			}
		const big = encodeQr('V', { version: 12 });
		for (const copy of [1, 2]) {
			let bits = 0;
			for (let y = 0; y < big.size; y++)
				for (let x = 0; x < big.size; x++) {
					const m = big.info[y][x];
					if (m.role === 'version' && m.copy === copy && big.modules[y][x]) bits |= 1 << m.bit;
				}
			expect(bits).toBe(versionBits(12));
		}
	});
});

test.describe('the layout', () => {
	test('alignment pattern centres match the standard table', () => {
		expect(alignmentPositions(1)).toEqual([]);
		expect(alignmentPositions(2)).toEqual([6, 18]);
		expect(alignmentPositions(7)).toEqual([6, 22, 38]);
		expect(alignmentPositions(14)).toEqual([6, 26, 46, 66]);
		expect(alignmentPositions(21)).toEqual([6, 28, 50, 72, 94]);
		expect(alignmentPositions(32)).toEqual([6, 34, 60, 86, 112, 138]);
		expect(alignmentPositions(36)).toEqual([6, 24, 50, 76, 102, 128, 154]);
		expect(alignmentPositions(40)).toEqual([6, 30, 58, 86, 114, 142, 170]);
	});

	test('function patterns sit where the standard puts them, in every version', () => {
		for (let v = 1; v <= 40; v++) {
			const qr = encodeQr('1', { version: v, ec: 'L' });
			const n = symbolSize(v);
			const at = (x: number, y: number) => qr.modules[y][x];
			// Finder patterns: a dark ring, a light ring, a dark 3×3 centre.
			const wrong: string[] = [];
			for (const [ox, oy] of [
				[0, 0],
				[n - 7, 0],
				[0, n - 7]
			])
				for (let dy = 0; dy < 7; dy++)
					for (let dx = 0; dx < 7; dx++) {
						const ring = Math.max(Math.abs(dx - 3), Math.abs(dy - 3));
						if (at(ox + dx, oy + dy) !== (ring !== 2) || qr.info[oy + dy][ox + dx].role !== 'finder')
							wrong.push(`finder ${ox + dx},${oy + dy}`);
					}
			// Timing patterns alternate between the finders, starting dark.
			for (let i = 8; i < n - 8; i++) {
				if (qr.info[6][i].role === 'timing' && at(i, 6) !== (i % 2 === 0)) wrong.push(`timing ${i},6`);
				if (qr.info[i][6].role === 'timing' && at(6, i) !== (i % 2 === 0)) wrong.push(`timing 6,${i}`);
			}
			// The dark module.
			expect(at(8, 4 * v + 9)).toBe(true);
			expect(qr.info[4 * v + 9][8].role).toBe('dark');
			// Separators are light.
			let separators = 0;
			for (let y = 0; y < n; y++)
				for (let x = 0; x < n; x++)
					if (qr.info[y][x].role === 'separator') {
						separators++;
						if (at(x, y)) wrong.push(`separator ${x},${y}`);
					}
			expect(wrong).toEqual([]);
			expect(separators).toBe(3 * 15);
			// Every module left over for codewords is used, and nothing else.
			let free = 0;
			for (const row of qr.info) for (const m of row) if (['data', 'ec', 'remainder'].includes(m.role)) free++;
			expect(free).toBe(rawDataModules(v));
			const roles = qr.info.flat();
			expect(roles.filter((m) => m.role === 'remainder')).toHaveLength(remainderBits(v));
			expect(roles.filter((m) => m.role === 'version')).toHaveLength(v >= 7 ? 36 : 0);
			expect(roles.filter((m) => m.role === 'format')).toHaveLength(30);
		}
	});

	test('each codeword is eight modules, bit 7 placed first', () => {
		const qr = encodeQr('https://logicgates.org/qr-code-generator', { ec: 'M' });
		const bits: number[][] = qr.sequence.map(() => []);
		for (const row of qr.info) for (const m of row) if (m.codeword >= 0) bits[m.codeword].push(m.bit);
		for (const b of bits) expect(b.sort()).toEqual([0, 1, 2, 3, 4, 5, 6, 7]);
		// The first codeword starts in the bottom right corner, going up.
		expect(qr.info[qr.size - 1][qr.size - 1]).toMatchObject({ codeword: 0, bit: 7 });
		expect(qr.info[qr.size - 1][qr.size - 2]).toMatchObject({ codeword: 0, bit: 6 });
		expect(qr.info[qr.size - 2][qr.size - 1]).toMatchObject({ codeword: 0, bit: 5 });
	});
});

test.describe('masks and penalties', () => {
	test('the mask inverts data and error correction modules only', () => {
		for (let mask = 0; mask < 8; mask++) {
			const qr = encodeQr('MASK TEST 123', { ec: 'H', version: 7, mask });
			const wrong: string[] = [];
			for (let y = 0; y < qr.size; y++)
				for (let x = 0; x < qr.size; x++) {
					const role = qr.info[y][x].role;
					const flip = ['data', 'ec', 'remainder'].includes(role) && MASKS[mask].test(x, y);
					if (qr.modules[y][x] !== (qr.unmasked[y][x] !== flip)) wrong.push(`${x},${y}`);
				}
			expect(wrong).toEqual([]);
		}
	});

	test('the automatic choice is the lowest total, and every total adds up', () => {
		const random = rng(3);
		for (let n = 0; n < 20; n++) {
			const text = String(Math.floor(random() * 1e9)) + 'abc'.repeat(Math.floor(random() * 30));
			const qr = encodeQr(text, { ec: EC_LEVELS[n % 4] });
			const lowest = Math.min(...qr.penalties.map((p) => p.total));
			expect(qr.penalties[qr.mask].total).toBe(lowest);
			expect(qr.penalties.findIndex((p) => p.total === lowest)).toBe(qr.mask);
			for (const p of qr.penalties) expect(p.total).toBe(p.runs + p.boxes + p.finders + p.balance);
			expect(penalty(qr.modules).total).toBe(lowest);
		}
	});

	// The standard only says to pick the lowest score; on a tie we keep the
	// lowest-numbered mask, so the choice is stable. These inputs tie for real.
	test('a tie for the lowest total goes to the lowest-numbered mask', () => {
		const ties: [string, EcLevel, number[]][] = [
			['32', 'L', [2, 5]],
			['51', 'Q', [0, 7]],
			['193', 'L', [3, 7]]
		];
		for (const [text, ec, tied] of ties) {
			const qr = encodeQr(text, { ec });
			const lowest = Math.min(...qr.penalties.map((p) => p.total));
			expect(
				qr.penalties.filter((p) => p.total === lowest).map((p) => p.mask),
				text
			).toEqual(tied);
			expect(qr.mask, text).toBe(tied[0]);
		}
	});

	test('the four rules on hand-made patterns', () => {
		const blank = Array.from({ length: 21 }, () => new Array(21).fill(false));
		// 42 lines of 21: 3 + 16 each; 20×20 boxes of 3; no finder lookalikes; 0% dark is 10 steps of 5%.
		expect(penalty(blank)).toMatchObject({ runs: 42 * 19, boxes: 1200, finders: 0, balance: 100 });
		const checker = blank.map((row, y) => row.map((_, x) => (x + y) % 2 === 0));
		// 221 of 441 dark is 50.1%: under one 5% step.
		expect(penalty(checker)).toMatchObject({ runs: 0, boxes: 0, finders: 0, balance: 0 });
		// One finder-like row with light on both sides counts twice.
		const row = blank.map((r) => r.slice());
		[1, 0, 1, 1, 1, 0, 1].forEach((d, i) => (row[10][7 + i] = d === 1));
		expect(penalty(row).finders).toBe(80);
	});

	test('the real finder patterns score the same 720 in every mask', () => {
		for (const v of [1, 2, 7, 21, 40]) expect(finderBaseline(symbolSize(v))).toBe(18 * 40);
		for (const text of ['HELLO WORLD', 'https://logicgates.org', '0'.repeat(300)]) {
			const qr = encodeQr(text, { ec: 'M' });
			for (const p of qr.penalties) expect(p.finders).toBeGreaterThanOrEqual(720);
		}
	});
});

test.describe('drawing and errors', () => {
	test('outlines, labels, role paths and the SVG', () => {
		const qr = encodeQr('HELLO WORLD', { ec: 'Q' });
		const labels = codewordLabels(qr);
		expect(labels).toHaveLength(26);
		expect(labels.filter((l) => l.kind === 'data')).toHaveLength(13);
		for (const l of labels) {
			expect(l.x).toBeGreaterThan(0);
			expect(l.x).toBeLessThan(21);
		}
		expect(codewordOutlines(qr)).toMatch(/^M/);
		const paths = rolePaths(qr);
		expect(paths.finder.dark).toContain('M0 0h7v1h-7z');
		expect(paths.separator.dark).toBe('');
		const svg = qrSvg(qr.modules, 10);
		expect(svg).toContain('width="290"');
		expect(svg).toContain('viewBox="0 0 29 29"');
		expect(describeModule(qr, 20, 20)).toContain('codeword 1 (data 1 of block 1, 0x20), bit 7');
		expect(describeModule(qr, 8, 13)).toContain('the dark module');
		// Before masking the readout follows the unmasked module, not the finished one.
		for (let y = 0; y < qr.size; y++)
			for (let x = 0; x < qr.size; x++) {
				if (!['data', 'ec'].includes(qr.info[y][x].role)) continue;
				const before = describeModule(qr, x, y, false);
				expect(before).not.toContain('inverted');
				expect(before).toContain(`before masking the module is ${qr.unmasked[y][x] ? 'dark' : 'light'}`);
				expect(describeModule(qr, x, y)).toContain(`the module is ${qr.modules[y][x] ? 'dark' : 'light'}`);
			}
	});

	test('errors say what is wrong', () => {
		expect(errorOf(() => encodeQr('x'.repeat(2954), { ec: 'L' }))).toMatch(/2,954 bytes.*largest QR code holds 2,953/);
		expect(errorOf(() => encodeQr('x', { ec: 'Z' as EcLevel }))).toMatch(/L, M, Q or H/);
		expect(errorOf(() => encodeQr('x'.repeat(1300), { ec: 'H' }))).toMatch(/lower error correction level/);
		expect(errorOf(() => encodeQr('x'.repeat(30), { version: 1 }))).toMatch(/smallest version that holds it is 3/);
		expect(errorOf(() => encodeQr('x', { version: 41 }))).toMatch(/version 1 to 40/);
		expect(errorOf(() => encodeQr('x', { mask: 8 }))).toMatch(/0 to 7/);
	});
});

test.describe('the qr-code-generator page', () => {
	test('the prerendered page shows a finished HELLO WORLD code', async ({ page }) => {
		const html = await (await page.request.get('/qr-code-generator')).text();
		expect(html).toContain('Version 1, 21 × 21 modules, level Q, mask 0');
		expect(html).toContain('20 5B 0B 78 D1 72 DC 4D 43 40 EC 11 EC');
		expect(html).toContain('A8 48 16 52 D9 36 9C 00 2E 0F B4 7A 10');
		expect(html).toMatch(/<svg[^>]*class="symbol/);
		// The worked example is a different code from the tool's default.
		expect(html).toContain('10 20 0C 56 61 80 EC 11 EC 11 EC 11 EC 11 EC 11');
		expect(html).toContain('A5 24 D4 C1 ED 36 C7 87 2C 55');
	});

	test('choosing a mask from the table keeps the focus there and says so', async ({ page }) => {
		await page.goto('/qr-code-generator');
		await page.waitForLoadState('networkidle');
		await page.locator('tr[data-mask="3"] .use-btn').click();
		await expect(page.locator('.answer')).toContainText('mask 3');
		await expect(page.locator('tr[data-mask="3"] .use-btn')).toBeFocused();
		await expect(page.locator('tr[data-mask="3"] .use-btn')).toHaveText('Back to auto');
		await expect(page.getByText('Mask 3 applied.')).toHaveCount(1);
		await page.keyboard.press('Enter');
		await expect(page.locator('.answer')).toContainText('mask 0');
		await expect(page.locator('tr[data-mask="3"] .use-btn')).toBeFocused();
	});

	test('a link whose text does not fit offers the way out and hides the unrelated code', async ({ page }) => {
		await page.goto('/qr-code-generator?t=' + 'abcdefghij'.repeat(5) + '&v=1&m=9');
		await page.waitForLoadState('networkidle');
		await expect(page.locator('.error')).toContainText('smallest version that holds it is 5');
		await expect(page.locator('.results')).toBeHidden();
		// The invalid mask is dropped from the address; the rest stays.
		await expect(page).not.toHaveURL(/m=9/);
		await expect(page).toHaveURL(/v=1/);
		await page.getByRole('button', { name: 'Use the smallest version, 5' }).click();
		await expect(page.locator('.answer')).toContainText('Version 5, 37 × 37 modules');
		await expect(page.locator('.error')).toHaveCount(0);
		// A path is case sensitive, so no capitals hint for it.
		await page.locator('#qr-text').fill('https://example.com/some/path');
		await expect(page.locator('.answer')).toContainText('byte mode');
		await expect(page.locator('.answer')).not.toContainText('In capitals');
	});

	test('typing re-encodes, settings change the code, and bad input explains itself', async ({ page }) => {
		await page.goto('/qr-code-generator');
		await page.waitForLoadState('networkidle');
		const answer = page.locator('.answer');
		await page.locator('#qr-text').fill('https://logicgates.org');
		await expect(answer).toContainText('22 bytes in byte mode');
		await expect(answer).toContainText('In capitals it would fit alphanumeric mode');
		await page.getByRole('button', { name: 'H 30%' }).click();
		await expect(answer).toContainText('level H');
		await page.locator('#qr-version').selectOption('10');
		await expect(answer).toContainText('Version 10, 57 × 57 modules');
		await expect(answer).toContainText('Version 3 would have been enough');
		await page.locator('#qr-mask').selectOption('5');
		await expect(answer).toContainText('mask 5');
		await expect(page.locator('.penalties tr.chosen')).toContainText('set');
		// Version information appears from version 7.
		await expect(page.locator('.layer', { hasText: 'Version information' })).toContainText('36');

		await page.locator('#qr-version').selectOption('auto');
		await page.locator('#qr-text').fill('x'.repeat(1300));
		await expect(page.locator('.error')).toContainText('lower error correction level');
		await page.locator('#qr-text').fill('');
		await expect(page.locator('.error')).toContainText('Type some text');
	});

	test('the inspector names the module under the pointer and the arrow keys', async ({ page }) => {
		await page.goto('/qr-code-generator');
		await page.waitForLoadState('networkidle');
		const symbol = page.locator('svg.symbol');
		await symbol.focus();
		await page.keyboard.press('ArrowUp');
		await expect(page.locator('#qr-readout')).toContainText('Row 20, column 20: codeword 1');
		await page.keyboard.press('ArrowLeft');
		await expect(page.locator('#qr-readout')).toContainText('Row 20, column 19: codeword 1');
		const box = await symbol.boundingBox();
		if (!box) throw new Error('the symbol has no box');
		const unit = box.width / 29;
		await page.mouse.move(box.x + unit * (4 + 8.5), box.y + unit * (4 + 13.5));
		await expect(page.locator('#qr-readout')).toContainText('the dark module');
		await page.getByRole('checkbox', { name: /Apply mask/ }).uncheck();
		await expect(page.locator('.anatomy')).toContainText('before masking');
	});

	test('the SVG download is the plain code with its quiet zone', async ({ page }) => {
		await page.goto('/qr-code-generator');
		await page.waitForLoadState('networkidle');
		const [download] = await Promise.all([
			page.waitForEvent('download'),
			page.getByRole('button', { name: 'Download SVG' }).click()
		]);
		expect(download.suggestedFilename()).toBe('qr-code-v1-Q.svg');
		const path = await download.path();
		const svg = (await import('node:fs')).readFileSync(path ?? '', 'utf8');
		expect(svg).toContain('viewBox="0 0 29 29"');
		expect(svg).toContain('fill="#000"');
	});

	test('a shared link reopens the same code, and the URL follows the settings', async ({ page }) => {
		await page.goto('/qr-code-generator?t=Hello%2C+world&ec=L&v=4&m=3');
		await page.waitForLoadState('networkidle');
		await expect(page.locator('#qr-text')).toHaveValue('Hello, world');
		await expect(page.locator('.answer')).toContainText('Version 4, 33 × 33 modules, level L, mask 3');
		await page.getByRole('button', { name: 'M 15%' }).click();
		await expect(page).toHaveURL(/ec=M/);
		await expect(page).toHaveURL(/t=Hello%2C\+world/);
		await page.locator('.chips button', { hasText: 'HELLO WORLD' }).click();
		await expect(page).toHaveURL(/\/qr-code-generator$/);
	});

	test('the FAQ markup matches the questions on the page', async ({ page }) => {
		await page.goto('/qr-code-generator');
		const blocks = await page.locator('script[type="application/ld+json"]').allTextContents();
		const graph = blocks.flatMap((text) => JSON.parse(text)['@graph'] ?? []);
		const webPage = graph.find((node: { '@type': string[] }) => [node['@type']].flat().includes('FAQPage'));
		const questions = webPage.mainEntity.map((q: { name: string }) => q.name);
		const answers = webPage.mainEntity.map((q: { acceptedAnswer: { text: string } }) => q.acceptedAnswer.text);
		expect(questions).toEqual((await page.locator('.faq summary').allTextContents()).map((t) => t.trim()));
		expect(answers).toEqual((await page.locator('.faq details > p').allTextContents()).map((t) => t.trim()));
	});
});
