// C struct layout, checked against clang rather than against hand-worked
// answers.
//
// The fixtures below were produced during development by compiling each struct
// with clang 18 for each target triple (clang -std=c2x -ffreestanding -target
// <triple> -S -emit-llvm, with the struct followed by globals initialised to
// sizeof, _Alignof and offsetof of every named member) and reading the numbers
// back from the IR. A null target means clang rejected the struct there. The
// same harness also passed 1,500 randomly generated structs (nesting, arrays,
// pack values, the packed attribute and _Alignas mixed) on all five targets.

import { expect, test, type Page } from '@playwright/test';
import {
	analyse,
	byteGrid,
	compareTargets,
	explainSteps,
	layoutRecord,
	paddingMask,
	parseStructs,
	recordCode,
	reorder,
	staticAsserts,
	targetById,
	typeText,
	StructError,
	TARGETS,
	type TargetId
} from '../src/lib/structLayout.js';

type Expected = [size: number, align: number, offsets: number[]] | null;
type Fixture = { name: string; src: string } & Record<TargetId, Expected>;

// Generated by clang; see the comment at the top. Do not edit by hand.
const FIXTURES: Fixture[] = [
	{
		name: 'bad order',
		src: 'struct packet { char tag; double value; short id; int count; char flag; };',
		x64: [32, 8, [0, 8, 16, 20, 24]],
		win64: [32, 8, [0, 8, 16, 20, 24]],
		i386: [24, 4, [0, 4, 12, 16, 20]],
		arm32: [32, 8, [0, 8, 16, 20, 24]],
		arm64: [32, 8, [0, 8, 16, 20, 24]]
	},
	{
		name: 'good order',
		src: 'struct packet { double value; int count; short id; char tag; char flag; };',
		x64: [16, 8, [0, 8, 12, 14, 15]],
		win64: [16, 8, [0, 8, 12, 14, 15]],
		i386: [16, 4, [0, 8, 12, 14, 15]],
		arm32: [16, 8, [0, 8, 12, 14, 15]],
		arm64: [16, 8, [0, 8, 12, 14, 15]]
	},
	{
		name: 'point',
		src: 'struct point { int x; int y; };',
		x64: [8, 4, [0, 4]],
		win64: [8, 4, [0, 4]],
		i386: [8, 4, [0, 4]],
		arm32: [8, 4, [0, 4]],
		arm64: [8, 4, [0, 4]]
	},
	{
		name: 'char then int',
		src: 'struct s { char c; int i; };',
		x64: [8, 4, [0, 4]],
		win64: [8, 4, [0, 4]],
		i386: [8, 4, [0, 4]],
		arm32: [8, 4, [0, 4]],
		arm64: [8, 4, [0, 4]]
	},
	{
		name: 'int then char',
		src: 'struct s { int i; char c; };',
		x64: [8, 4, [0, 4]],
		win64: [8, 4, [0, 4]],
		i386: [8, 4, [0, 4]],
		arm32: [8, 4, [0, 4]],
		arm64: [8, 4, [0, 4]]
	},
	{
		name: 'all chars',
		src: 'struct rgb { unsigned char r, g, b; };',
		x64: [3, 1, [0, 1, 2]],
		win64: [3, 1, [0, 1, 2]],
		i386: [3, 1, [0, 1, 2]],
		arm32: [3, 1, [0, 1, 2]],
		arm64: [3, 1, [0, 1, 2]]
	},
	{
		name: 'short char short',
		src: 'struct s { short a; char b; short c; };',
		x64: [6, 2, [0, 2, 4]],
		win64: [6, 2, [0, 2, 4]],
		i386: [6, 2, [0, 2, 4]],
		arm32: [6, 2, [0, 2, 4]],
		arm64: [6, 2, [0, 2, 4]]
	},
	{
		name: 'long',
		src: 'struct s { char c; long l; };',
		x64: [16, 8, [0, 8]],
		win64: [8, 4, [0, 4]],
		i386: [8, 4, [0, 4]],
		arm32: [8, 4, [0, 4]],
		arm64: [16, 8, [0, 8]]
	},
	{
		name: 'long long',
		src: 'struct s { char c; long long ll; };',
		x64: [16, 8, [0, 8]],
		win64: [16, 8, [0, 8]],
		i386: [12, 4, [0, 4]],
		arm32: [16, 8, [0, 8]],
		arm64: [16, 8, [0, 8]]
	},
	{
		name: 'double',
		src: 'struct s { char c; double d; };',
		x64: [16, 8, [0, 8]],
		win64: [16, 8, [0, 8]],
		i386: [12, 4, [0, 4]],
		arm32: [16, 8, [0, 8]],
		arm64: [16, 8, [0, 8]]
	},
	{
		name: 'long double',
		src: 'struct s { char c; long double ld; char e; };',
		x64: [48, 16, [0, 16, 32]],
		win64: [24, 8, [0, 8, 16]],
		i386: [20, 4, [0, 4, 16]],
		arm32: [24, 8, [0, 8, 16]],
		arm64: [48, 16, [0, 16, 32]]
	},
	{
		name: 'pointers',
		src: 'struct node { int value; struct node *next; };',
		x64: [16, 8, [0, 8]],
		win64: [16, 8, [0, 8]],
		i386: [8, 4, [0, 4]],
		arm32: [8, 4, [0, 4]],
		arm64: [16, 8, [0, 8]]
	},
	{
		name: 'pointer to pointer',
		src: 'struct argv { int argc; char **argv; char *env[3]; };',
		x64: [40, 8, [0, 8, 16]],
		win64: [40, 8, [0, 8, 16]],
		i386: [20, 4, [0, 4, 8]],
		arm32: [20, 4, [0, 4, 8]],
		arm64: [40, 8, [0, 8, 16]]
	},
	{
		name: 'size_t family',
		src: '#include <stddef.h>\n#include <stdint.h>\nstruct buf { char tag; size_t len; ptrdiff_t diff; intptr_t ip; uintptr_t up; };',
		x64: [40, 8, [0, 8, 16, 24, 32]],
		win64: [40, 8, [0, 8, 16, 24, 32]],
		i386: [20, 4, [0, 4, 8, 12, 16]],
		arm32: [20, 4, [0, 4, 8, 12, 16]],
		arm64: [40, 8, [0, 8, 16, 24, 32]]
	},
	{
		name: 'stdint',
		src: '#include <stdint.h>\nstruct hdr { uint8_t version; uint16_t flags; uint32_t length; uint64_t id; int8_t s; };',
		x64: [24, 8, [0, 2, 4, 8, 16]],
		win64: [24, 8, [0, 2, 4, 8, 16]],
		i386: [20, 4, [0, 2, 4, 8, 16]],
		arm32: [24, 8, [0, 2, 4, 8, 16]],
		arm64: [24, 8, [0, 2, 4, 8, 16]]
	},
	{
		name: 'int64_t on i386',
		src: '#include <stdint.h>\nstruct s { uint32_t a; int64_t b; uint8_t c; };',
		x64: [24, 8, [0, 8, 16]],
		win64: [24, 8, [0, 8, 16]],
		i386: [16, 4, [0, 4, 12]],
		arm32: [24, 8, [0, 8, 16]],
		arm64: [24, 8, [0, 8, 16]]
	},
	{
		name: 'bool',
		src: '#include <stdbool.h>\nstruct flags { bool a; _Bool b; int n; bool c; };',
		x64: [12, 4, [0, 1, 4, 8]],
		win64: [12, 4, [0, 1, 4, 8]],
		i386: [12, 4, [0, 1, 4, 8]],
		arm32: [12, 4, [0, 1, 4, 8]],
		arm64: [12, 4, [0, 1, 4, 8]]
	},
	{
		name: 'wchar',
		src: '#include <stddef.h>\nstruct w { char c; wchar_t w; char d; };',
		x64: [12, 4, [0, 4, 8]],
		win64: [6, 2, [0, 2, 4]],
		i386: [12, 4, [0, 4, 8]],
		arm32: [12, 4, [0, 4, 8]],
		arm64: [12, 4, [0, 4, 8]]
	},
	{
		name: 'float mix',
		src: 'struct v { float x; double y; float z; };',
		x64: [24, 8, [0, 8, 16]],
		win64: [24, 8, [0, 8, 16]],
		i386: [16, 4, [0, 4, 12]],
		arm32: [24, 8, [0, 8, 16]],
		arm64: [24, 8, [0, 8, 16]]
	},
	{
		name: '2d array',
		src: 'struct grid { char name[5]; short cells[3][3]; int n; };',
		x64: [28, 4, [0, 6, 24]],
		win64: [28, 4, [0, 6, 24]],
		i386: [28, 4, [0, 6, 24]],
		arm32: [28, 4, [0, 6, 24]],
		arm64: [28, 4, [0, 6, 24]]
	},
	{
		name: 'array of structs',
		src: 'struct point { short x, y; };\nstruct poly { char n; struct point pts[3]; };',
		x64: [14, 2, [0, 2]],
		win64: [14, 2, [0, 2]],
		i386: [14, 2, [0, 2]],
		arm32: [14, 2, [0, 2]],
		arm64: [14, 2, [0, 2]]
	},
	{
		name: 'nested',
		src: 'struct inner { char a; int b; };\nstruct outer { char c; struct inner in; char d; };',
		x64: [16, 4, [0, 4, 12]],
		win64: [16, 4, [0, 4, 12]],
		i386: [16, 4, [0, 4, 12]],
		arm32: [16, 4, [0, 4, 12]],
		arm64: [16, 4, [0, 4, 12]]
	},
	{
		name: 'nested inline',
		src: 'struct outer { char c; struct { double d; char e; } in; short s; };',
		x64: [32, 8, [0, 8, 24]],
		win64: [32, 8, [0, 8, 24]],
		i386: [20, 4, [0, 4, 16]],
		arm32: [32, 8, [0, 8, 24]],
		arm64: [32, 8, [0, 8, 24]]
	},
	{
		name: 'nested tagged inline',
		src: 'struct outer { char c; struct inner { long long v; char t; } in; struct inner more; };',
		x64: [40, 8, [0, 8, 24]],
		win64: [40, 8, [0, 8, 24]],
		i386: [28, 4, [0, 4, 16]],
		arm32: [40, 8, [0, 8, 24]],
		arm64: [40, 8, [0, 8, 24]]
	},
	{
		name: 'union',
		src: 'union value { int i; double d; char s[10]; };',
		x64: [16, 8, [0, 0, 0]],
		win64: [16, 8, [0, 0, 0]],
		i386: [12, 4, [0, 0, 0]],
		arm32: [16, 8, [0, 0, 0]],
		arm64: [16, 8, [0, 0, 0]]
	},
	{
		name: 'tagged union',
		src: 'struct value { int kind; union { long i; double d; char s[12]; } as; };',
		x64: [24, 8, [0, 8]],
		win64: [24, 8, [0, 8]],
		i386: [16, 4, [0, 4]],
		arm32: [24, 8, [0, 8]],
		arm64: [24, 8, [0, 8]]
	},
	{
		name: 'anonymous union',
		src: 'struct value { int kind; union { int i; float f; }; char c; };',
		x64: [12, 4, [0, 8]],
		win64: [12, 4, [0, 8]],
		i386: [12, 4, [0, 8]],
		arm32: [12, 4, [0, 8]],
		arm64: [12, 4, [0, 8]]
	},
	{
		name: 'union in struct',
		src: 'union u { char c[5]; int i; };\nstruct s { char a; union u x; char b; };',
		x64: [16, 4, [0, 4, 12]],
		win64: [16, 4, [0, 4, 12]],
		i386: [16, 4, [0, 4, 12]],
		arm32: [16, 4, [0, 4, 12]],
		arm64: [16, 4, [0, 4, 12]]
	},
	{
		name: 'pragma pack 1',
		src: '#pragma pack(1)\nstruct header { char magic; int length; short type; double stamp; };\n#pragma pack()',
		x64: [15, 1, [0, 1, 5, 7]],
		win64: [15, 1, [0, 1, 5, 7]],
		i386: [15, 1, [0, 1, 5, 7]],
		arm32: [15, 1, [0, 1, 5, 7]],
		arm64: [15, 1, [0, 1, 5, 7]]
	},
	{
		name: 'pragma pack 2',
		src: '#pragma pack(2)\nstruct s { char c; double d; char e; int i; };\n#pragma pack()',
		x64: [16, 2, [0, 2, 10, 12]],
		win64: [16, 2, [0, 2, 10, 12]],
		i386: [16, 2, [0, 2, 10, 12]],
		arm32: [16, 2, [0, 2, 10, 12]],
		arm64: [16, 2, [0, 2, 10, 12]]
	},
	{
		name: 'pragma pack 4',
		src: '#pragma pack(4)\nstruct s { char c; double d; long double ld; };\n#pragma pack()',
		x64: [28, 4, [0, 4, 12]],
		win64: [20, 4, [0, 4, 12]],
		i386: [24, 4, [0, 4, 12]],
		arm32: [20, 4, [0, 4, 12]],
		arm64: [28, 4, [0, 4, 12]]
	},
	{
		name: 'pragma pack push pop',
		src: '#pragma pack(push, 2)\nstruct a { char c; int i; };\n#pragma pack(pop)\nstruct b { char c; struct a x; long long y; };',
		x64: [16, 8, [0, 2, 8]],
		win64: [16, 8, [0, 2, 8]],
		i386: [16, 4, [0, 2, 8]],
		arm32: [16, 8, [0, 2, 8]],
		arm64: [16, 8, [0, 2, 8]]
	},
	{
		name: 'pragma pack 16',
		src: '#pragma pack(16)\nstruct s { char c; long double d; };\n#pragma pack()',
		x64: [32, 16, [0, 16]],
		win64: [16, 8, [0, 8]],
		i386: [16, 4, [0, 4]],
		arm32: [16, 8, [0, 8]],
		arm64: [32, 16, [0, 16]]
	},
	{
		name: 'packed attribute',
		src: 'struct __attribute__((packed)) wire { unsigned char type; unsigned int length; unsigned short port; };',
		x64: [7, 1, [0, 1, 5]],
		win64: [7, 1, [0, 1, 5]],
		i386: [7, 1, [0, 1, 5]],
		arm32: [7, 1, [0, 1, 5]],
		arm64: [7, 1, [0, 1, 5]]
	},
	{
		name: 'packed after brace',
		src: 'struct wire { char a; long long b; short c; } __attribute__((packed));',
		x64: [11, 1, [0, 1, 9]],
		win64: [11, 1, [0, 1, 9]],
		i386: [11, 1, [0, 1, 9]],
		arm32: [11, 1, [0, 1, 9]],
		arm64: [11, 1, [0, 1, 9]]
	},
	{
		name: 'packed nested',
		src: 'struct inner { char a; int b; };\nstruct __attribute__((packed)) outer { char c; struct inner in; };',
		x64: [9, 1, [0, 1]],
		win64: [9, 1, [0, 1]],
		i386: [9, 1, [0, 1]],
		arm32: [9, 1, [0, 1]],
		arm64: [9, 1, [0, 1]]
	},
	{
		name: 'contains packed',
		src: 'struct __attribute__((packed)) p { char c; int x; };\nstruct s { char a; struct p in; int z; };',
		x64: [12, 4, [0, 1, 8]],
		win64: [12, 4, [0, 1, 8]],
		i386: [12, 4, [0, 1, 8]],
		arm32: [12, 4, [0, 1, 8]],
		arm64: [12, 4, [0, 1, 8]]
	},
	{
		name: 'alignas number',
		src: 'struct s { char c; _Alignas(16) int x; char d; };',
		x64: [32, 16, [0, 16, 20]],
		win64: [32, 16, [0, 16, 20]],
		i386: [32, 16, [0, 16, 20]],
		arm32: [32, 16, [0, 16, 20]],
		arm64: [32, 16, [0, 16, 20]]
	},
	{
		name: 'alignas type',
		src: 'struct s { char c; _Alignas(double) char d; };',
		x64: [16, 8, [0, 8]],
		win64: [16, 8, [0, 8]],
		i386: [8, 4, [0, 4]],
		arm32: [16, 8, [0, 8]],
		arm64: [16, 8, [0, 8]]
	},
	{
		name: 'alignas keyword',
		src: 'struct counters { alignas(64) long hits; alignas(64) long misses; };',
		x64: [128, 64, [0, 64]],
		win64: [128, 64, [0, 64]],
		i386: [128, 64, [0, 64]],
		arm32: [128, 64, [0, 64]],
		arm64: [128, 64, [0, 64]]
	},
	{
		name: 'alignas long long',
		src: 'struct s { char c; _Alignas(long long) char d; };',
		x64: [16, 8, [0, 8]],
		win64: [16, 8, [0, 8]],
		i386: [8, 4, [0, 4]],
		arm32: [16, 8, [0, 8]],
		arm64: [16, 8, [0, 8]]
	},
	{
		name: 'alignas under pack',
		src: '#pragma pack(push, 1)\nstruct s { char c; _Alignas(8) int x; };\n#pragma pack(pop)',
		x64: [5, 1, [0, 1]],
		win64: [16, 8, [0, 8]],
		i386: [5, 1, [0, 1]],
		arm32: [5, 1, [0, 1]],
		arm64: [5, 1, [0, 1]]
	},
	{
		name: 'alignas under pack 2',
		src: '#pragma pack(2)\nstruct s { char c; _Alignas(8) double d; };\n#pragma pack()',
		x64: [10, 2, [0, 2]],
		win64: [16, 8, [0, 8]],
		i386: [10, 2, [0, 2]],
		arm32: [10, 2, [0, 2]],
		arm64: [10, 2, [0, 2]]
	},
	{
		name: 'alignas packed',
		src: 'struct __attribute__((packed)) s { char c; _Alignas(8) int x; double d; };',
		x64: [24, 8, [0, 8, 12]],
		win64: [24, 8, [0, 8, 12]],
		i386: [24, 8, [0, 8, 12]],
		arm32: [24, 8, [0, 8, 12]],
		arm64: [24, 8, [0, 8, 12]]
	},
	{
		name: 'alignas packed pragma',
		src: '#pragma pack(1)\nstruct __attribute__((packed)) s { char c; _Alignas(4) char x; double d; };\n#pragma pack()',
		x64: [10, 1, [0, 1, 2]],
		win64: [16, 4, [0, 4, 5]],
		i386: [10, 1, [0, 1, 2]],
		arm32: [10, 1, [0, 1, 2]],
		arm64: [10, 1, [0, 1, 2]]
	},
	{
		name: 'aligned inner under pack',
		src: 'struct in { char c; _Alignas(16) char d; };\n#pragma pack(1)\nstruct out { char c; struct in i; };\n#pragma pack()',
		x64: [33, 1, [0, 1]],
		win64: [48, 16, [0, 16]],
		i386: [33, 1, [0, 1]],
		arm32: [33, 1, [0, 1]],
		arm64: [33, 1, [0, 1]]
	},
	{
		name: 'aligned inner array',
		src: 'struct in { char c; _Alignas(16) char d; };\nstruct out { struct in arr[2]; char t; };',
		x64: [80, 16, [0, 64]],
		win64: [80, 16, [0, 64]],
		i386: [80, 16, [0, 64]],
		arm32: [80, 16, [0, 64]],
		arm64: [80, 16, [0, 64]]
	},
	{
		name: 'packed holds aligned inner',
		src: 'struct in { char c; _Alignas(16) char d; };\nstruct __attribute__((packed)) out { char c; struct in i; };',
		x64: [33, 1, [0, 1]],
		win64: [48, 16, [0, 16]],
		i386: [33, 1, [0, 1]],
		arm32: [33, 1, [0, 1]],
		arm64: [33, 1, [0, 1]]
	},
	{
		name: 'alignas 4 double',
		src: 'struct s { char c; _Alignas(4) double d; };',
		x64: null,
		win64: null,
		i386: [12, 4, [0, 4]],
		arm32: null,
		arm64: null
	},
	{
		name: 'function pointer',
		src: 'struct ops { char c; int (*open)(const char *path, int flags); void (*close)(int); };',
		x64: [24, 8, [0, 8, 16]],
		win64: [24, 8, [0, 8, 16]],
		i386: [12, 4, [0, 4, 8]],
		arm32: [12, 4, [0, 4, 8]],
		arm64: [24, 8, [0, 8, 16]]
	},
	{
		name: 'function pointer array',
		src: 'struct table { short n; void (*handlers[4])(void); };',
		x64: [40, 8, [0, 8]],
		win64: [40, 8, [0, 8]],
		i386: [20, 4, [0, 4]],
		arm32: [20, 4, [0, 4]],
		arm64: [40, 8, [0, 8]]
	},
	{
		name: 'flexible array',
		src: '#include <stdint.h>\nstruct msg { uint16_t len; uint8_t type; char data[]; };',
		x64: [4, 2, [0, 2, 3]],
		win64: [4, 2, [0, 2, 3]],
		i386: [4, 2, [0, 2, 3]],
		arm32: [4, 2, [0, 2, 3]],
		arm64: [4, 2, [0, 2, 3]]
	},
	{
		name: 'flexible int array',
		src: 'struct v { char c; int items[]; };',
		x64: [4, 4, [0, 4]],
		win64: [4, 4, [0, 4]],
		i386: [4, 4, [0, 4]],
		arm32: [4, 4, [0, 4]],
		arm64: [4, 4, [0, 4]]
	},
	{
		name: 'flexible double array',
		src: 'struct v { int n; double items[]; };',
		x64: [8, 8, [0, 8]],
		win64: [8, 8, [0, 8]],
		i386: [4, 4, [0, 4]],
		arm32: [8, 8, [0, 8]],
		arm64: [8, 8, [0, 8]]
	},
	{
		name: 'typedef struct',
		src: 'typedef struct { char c; double d; } pair;',
		x64: [16, 8, [0, 8]],
		win64: [16, 8, [0, 8]],
		i386: [12, 4, [0, 4]],
		arm32: [16, 8, [0, 8]],
		arm64: [16, 8, [0, 8]]
	},
	{
		name: 'typedef tagged',
		src: 'typedef struct vec3 { float x, y, z; } vec3;\nstruct obj { char id; vec3 pos; vec3 *vel; };',
		x64: [24, 8, [0, 4, 16]],
		win64: [24, 8, [0, 4, 16]],
		i386: [20, 4, [0, 4, 16]],
		arm32: [20, 4, [0, 4, 16]],
		arm64: [24, 8, [0, 4, 16]]
	},
	{
		name: 'typedef scalar',
		src: 'typedef unsigned long long u64;\ntypedef unsigned char u8;\nstruct s { u8 a; u64 b; u8 c[3]; };',
		x64: [24, 8, [0, 8, 16]],
		win64: [24, 8, [0, 8, 16]],
		i386: [16, 4, [0, 4, 12]],
		arm32: [24, 8, [0, 8, 16]],
		arm64: [24, 8, [0, 8, 16]]
	},
	{
		name: 'qualifiers',
		src: 'struct s { const char *name; volatile int counter; char *const p; unsigned const char u; };',
		x64: [32, 8, [0, 8, 16, 24]],
		win64: [32, 8, [0, 8, 16, 24]],
		i386: [16, 4, [0, 4, 8, 12]],
		arm32: [16, 4, [0, 4, 8, 12]],
		arm64: [32, 8, [0, 8, 16, 24]]
	},
	{
		name: 'long int spellings',
		src: 'struct s { short int a; long int b; unsigned long int c; long long int d; signed e; unsigned f; long unsigned g; };',
		x64: [48, 8, [0, 8, 16, 24, 32, 36, 40]],
		win64: [40, 8, [0, 4, 8, 16, 24, 28, 32]],
		i386: [32, 4, [0, 4, 8, 12, 20, 24, 28]],
		arm32: [40, 8, [0, 4, 8, 16, 24, 28, 32]],
		arm64: [48, 8, [0, 8, 16, 24, 32, 36, 40]]
	},
	{
		name: 'big',
		src: 'struct s { char a; double b[100]; char c; };',
		x64: [816, 8, [0, 8, 808]],
		win64: [816, 8, [0, 8, 808]],
		i386: [808, 4, [0, 4, 804]],
		arm32: [816, 8, [0, 8, 808]],
		arm64: [816, 8, [0, 8, 808]]
	},
	{
		name: 'many padding',
		src: 'struct s { char a; long long b; char c; long long d; char e; long long f; char g; };',
		x64: [56, 8, [0, 8, 16, 24, 32, 40, 48]],
		win64: [56, 8, [0, 8, 16, 24, 32, 40, 48]],
		i386: [40, 4, [0, 4, 12, 16, 24, 28, 36]],
		arm32: [56, 8, [0, 8, 16, 24, 32, 40, 48]],
		arm64: [56, 8, [0, 8, 16, 24, 32, 40, 48]]
	},
	{
		name: 'union with struct',
		src: 'struct pair { int a; char b; };\nunion u { struct pair p; long long l; char c; };',
		x64: [8, 8, [0, 0, 0]],
		win64: [8, 8, [0, 0, 0]],
		i386: [8, 4, [0, 0, 0]],
		arm32: [8, 8, [0, 0, 0]],
		arm64: [8, 8, [0, 0, 0]]
	},
	{
		name: 'nested union anon struct',
		src: 'union reg { unsigned int word; struct { unsigned short lo, hi; }; };',
		x64: [4, 4, [0]],
		win64: [4, 4, [0]],
		i386: [4, 4, [0]],
		arm32: [4, 4, [0]],
		arm64: [4, 4, [0]]
	},
	{
		name: 'bmp header packed',
		src: '#include <stdint.h>\n#pragma pack(push, 1)\nstruct bmp_file_header { char magic[2]; uint32_t size; uint16_t reserved1; uint16_t reserved2; uint32_t pixel_offset; };\n#pragma pack(pop)',
		x64: [14, 1, [0, 2, 6, 8, 10]],
		win64: [14, 1, [0, 2, 6, 8, 10]],
		i386: [14, 1, [0, 2, 6, 8, 10]],
		arm32: [14, 1, [0, 2, 6, 8, 10]],
		arm64: [14, 1, [0, 2, 6, 8, 10]]
	},
	{
		name: 'bmp header unpacked',
		src: '#include <stdint.h>\nstruct bmp_file_header { char magic[2]; uint32_t size; uint16_t reserved1; uint16_t reserved2; uint32_t pixel_offset; };',
		x64: [16, 4, [0, 4, 8, 10, 12]],
		win64: [16, 4, [0, 4, 8, 10, 12]],
		i386: [16, 4, [0, 4, 8, 10, 12]],
		arm32: [16, 4, [0, 4, 8, 10, 12]],
		arm64: [16, 4, [0, 4, 8, 10, 12]]
	},
	{
		name: 'sprite',
		src: 'struct point { short x, y; };\nstruct sprite { char visible; struct point pos; struct { double scale; char layer; } style; };',
		x64: [24, 8, [0, 2, 8]],
		win64: [24, 8, [0, 2, 8]],
		i386: [20, 4, [0, 2, 8]],
		arm32: [24, 8, [0, 2, 8]],
		arm64: [24, 8, [0, 2, 8]]
	},
	{
		name: 'message',
		src: '#include <stdint.h>\nstruct message { uint32_t length; uint8_t type; char data[]; };',
		x64: [8, 4, [0, 4, 5]],
		win64: [8, 4, [0, 4, 5]],
		i386: [8, 4, [0, 4, 5]],
		arm32: [8, 4, [0, 4, 5]],
		arm64: [8, 4, [0, 4, 5]]
	},
	{
		name: 'msvc long',
		src: 'struct s { char c; long l; long long ll; };',
		x64: [24, 8, [0, 8, 16]],
		win64: [16, 8, [0, 4, 8]],
		i386: [16, 4, [0, 4, 8]],
		arm32: [16, 8, [0, 4, 8]],
		arm64: [24, 8, [0, 8, 16]]
	}
];

const ids = TARGETS.map((t) => t.id);

/** Throws the engine's error, or returns null when it parses and lays out. */
function errorOf(src: string, target: TargetId = 'x64'): StructError | null {
	try {
		analyse(src, target);
		return null;
	} catch (e) {
		if (!(e instanceof StructError)) throw e;
		return e;
	}
}

test.describe('struct layout engine', () => {
	test('there are enough fixtures, covering every target', () => {
		expect(FIXTURES.length).toBeGreaterThanOrEqual(40);
		for (const f of FIXTURES) expect(Object.keys(f).sort()).toEqual(['name', 'src', ...ids].sort());
	});

	for (const fixture of FIXTURES) {
		test(`matches clang: ${fixture.name}`, () => {
			const program = parseStructs(fixture.src);
			for (const id of ids) {
				const expected = fixture[id];
				if (expected === null) {
					expect(() => layoutRecord(program.main, targetById(id)), `${id} should be rejected`).toThrow(StructError);
					continue;
				}
				const layout = layoutRecord(program.main, targetById(id));
				const offsets = layout.members.filter((m) => m.name).map((m) => m.offset);
				expect([layout.size, layout.align, offsets], id).toEqual(expected);
			}
		});
	}

	test('the target tables match the ABI facts the page states', () => {
		const t = (id: TargetId) => targetById(id).types;
		// LP64 against LLP64: long is the type that differs.
		expect(t('x64').long).toEqual([8, 8]);
		expect(t('win64').long).toEqual([4, 4]);
		// i386 System V: 8-byte types only 4-aligned inside structs, long double 12 bytes.
		expect(t('i386').double).toEqual([8, 4]);
		expect(t('i386')['long long']).toEqual([8, 4]);
		expect(t('i386')['long double']).toEqual([12, 4]);
		// AAPCS aligns double and long long to 8 even on 32-bit ARM.
		expect(t('arm32').double).toEqual([8, 8]);
		expect(t('arm32')['long double']).toEqual([8, 8]);
		expect(t('arm64')['long double']).toEqual([16, 16]);
		for (const target of TARGETS)
			for (const [name, [size, align]] of Object.entries(target.types)) {
				expect(align & (align - 1), `${target.id} ${name}`).toBe(0);
				expect(size % align === 0 || name === 'long double', `${target.id} ${name}`).toBe(true);
			}
	});

	test('layout invariants hold for random structs', () => {
		const types = ['char', 'short', 'int', 'long', 'long long', 'double', 'long double', 'float', 'void *', 'uint16_t'];
		const pick = <T>(a: T[]) => a[Math.floor(Math.random() * a.length)];
		for (let k = 0; k < 300; k++) {
			const n = 1 + Math.floor(Math.random() * 7);
			const members = Array.from({ length: n }, (_, i) => `${pick(types)} m${i}${Math.random() < 0.2 ? '[3]' : ''};`);
			const src = `struct s { ${members.join(' ')} };`;
			const program = parseStructs(src);
			for (const target of TARGETS) {
				const layout = layoutRecord(program.main, target);
				let end = 0;
				for (const m of layout.members) {
					expect(m.offset % m.align).toBe(0);
					expect(m.offset).toBe(end + m.paddingBefore);
					// No gap of a whole alignment unit: the compiler pads as little as it can.
					expect(m.paddingBefore).toBeLessThan(m.align);
					end = m.offset + m.size;
				}
				expect(layout.size % layout.align).toBe(0);
				expect(layout.size - end).toBe(layout.trailing);
				expect(layout.trailing).toBeLessThan(layout.align);
				expect(layout.align).toBe(Math.max(...layout.members.map((m) => m.align)));
				const data = layout.members.reduce((s, m) => s + m.size, 0);
				expect(layout.wasted).toBe(layout.size - data);
				expect(paddingMask(layout.gaps, layout.size).filter(Boolean)).toHaveLength(layout.wasted);

				// Sorting by alignment leaves no gaps between members, and the
				// reordered code parses back to that same layout.
				const sorted = layoutRecord(reorder(program.main, layout), target);
				expect(sorted.size).toBeLessThanOrEqual(layout.size);
				expect(sorted.members.every((m) => m.paddingBefore === 0)).toBe(true);
				const again = layoutRecord(parseStructs(recordCode(reorder(program.main, layout))).main, target);
				expect(again.size).toBe(sorted.size);
				expect(again.members.map((m) => m.offset)).toEqual(sorted.members.map((m) => m.offset));
			}
		}
	});

	test('the default example: a worked layout and its reordering', () => {
		const a = analyse(FIXTURES[0].src, 'x64');
		expect(a.layout.members.map((m) => [m.label, m.offset, m.paddingBefore])).toEqual([
			['tag', 0, 0],
			['value', 8, 7],
			['id', 16, 0],
			['count', 20, 2],
			['flag', 24, 0]
		]);
		expect(a.layout.trailing).toBe(7);
		expect(a.layout.wasted).toBe(16);
		expect(a.layout.wastedPercent).toBe(50);
		expect(a.reordered?.layout.size).toBe(16);
		expect(a.reordered?.saved).toBe(16);
		expect(a.reordered?.code).toBe(
			'struct packet {\n    double value;\n    int count;\n    short id;\n    char tag;\n    char flag;\n};'
		);
		const steps = explainSteps(a.layout);
		expect(steps[0]).toContain('first member always starts at offset 0');
		expect(steps[1]).toContain('offset 1 is not a multiple of 8, so 7 bytes of padding');
		expect(steps[steps.length - 1]).toContain('rounds up to 32 with 7 bytes of trailing padding');
	});

	test('nested padding is counted and drawn inside the member', () => {
		const a = analyse('struct in { char a; int b; };\nstruct out { char c; struct in i; };', 'x64');
		expect(a.layout.size).toBe(12);
		expect(a.layout.padding).toBe(3);
		expect(a.layout.innerPadding).toBe(3);
		expect(a.layout.wasted).toBe(6);
		expect(a.layout.members[1].innerPadding).toBe(3);
		const segs = byteGrid(a.layout).flatMap((r) => r.segments);
		expect(segs.map((s) => [s.member, s.innerPad, s.length])).toEqual([
			[0, false, 1],
			[-1, false, 3],
			[1, false, 1],
			[1, true, 3],
			[1, false, 4]
		]);
	});

	test('the byte grid splits rows of 8 and labels each member once per row', () => {
		const a = analyse(FIXTURES[0].src, 'x64');
		const rows = byteGrid(a.layout);
		expect(rows.map((r) => r.offset)).toEqual([0, 8, 16, 24]);
		for (const r of rows) expect(r.segments.reduce((s, x) => s + x.length, 0)).toBe(8);
		expect(rows[1].segments).toEqual([{ member: 1, innerPad: false, start: 8, length: 8, first: true }]);
		expect(byteGrid(analyse('struct s { char c[40]; };', 'x64').layout, 8, 16)).toHaveLength(2);
		// A union draws the largest member over the bytes it covers.
		const u = analyse('union u { char c; double d; };', 'x64').layout;
		expect(byteGrid(u)[0].segments).toEqual([{ member: 1, innerPad: false, start: 0, length: 8, first: true }]);
	});

	test('unions overlap at offset 0 and are never reordered', () => {
		const a = analyse('union u { char c[5]; int i; };', 'x64');
		expect(a.layout.members.map((m) => m.offset)).toEqual([0, 0]);
		expect(a.layout.size).toBe(8);
		expect(a.layout.trailing).toBe(3);
		expect(a.reordered).toBeNull();
		expect(explainSteps(a.layout)[0]).toContain('starts at offset 0');
	});

	test('type names read the way C writes them', () => {
		const m = parseStructs(
			'struct s { char *a[4]; char **b; int (*f)(int, char *); unsigned long long c[2][3]; struct s *next; };'
		).main.members;
		expect(m.map((x) => typeText(x.type))).toEqual([
			'char *[4]',
			'char **',
			'int (*)(int, char *)',
			'unsigned long long [2][3]',
			'struct s *'
		]);
	});

	test('pragma pack push and pop nest', () => {
		const src = `#pragma pack(push, 1)
struct a { char c; int i; };
#pragma pack(push, 2)
struct b { char c; int i; };
#pragma pack(pop)
struct c { char c; int i; };
#pragma pack(pop)
struct d { char c; int i; struct a x; struct b y; struct c z; };`;
		const p = parseStructs(src);
		expect(p.records.map((r) => r.pack)).toEqual([1, 2, 1, null]);
		// Offsets and size as clang gives them for x86_64-linux-gnu.
		const d = layoutRecord(p.main, targetById('x64'));
		expect(d.members.map((m) => m.offset)).toEqual([0, 4, 8, 14, 20]);
		expect(d.size).toBe(28);
	});

	test('the static asserts and the comparison table', () => {
		const a = analyse(FIXTURES[0].src, 'x64');
		const x64 = targetById('x64');
		expect(staticAsserts(a.layout, x64)).toContain('_Static_assert(offsetof(struct packet, value) == 8, "value");');
		expect(staticAsserts(a.layout, x64)).toContain('_Static_assert(sizeof(struct packet) == 32, "size");');
		// The checks say which target they hold for.
		expect(staticAsserts(a.layout, x64).split('\n')[0]).toBe(
			'/* Layout on x86-64 Linux and macOS (x86_64-linux-gnu) */'
		);
		const t = analyse('typedef struct { char c; double d; } pair;', 'i386');
		expect(staticAsserts(t.layout, targetById('i386'))).toContain('sizeof(pair) == 12');
		// An untagged struct is named by its variable; with nothing to name it, no checks.
		const v = analyse('struct { char c; double d; } x;', 'x64');
		expect(staticAsserts(v.layout, x64)).toContain('_Static_assert(sizeof(x) == 16, "size");');
		expect(staticAsserts(v.layout, x64)).toContain('_Static_assert(offsetof(__typeof__(x), d) == 8, "d");');
		expect(staticAsserts(v.layout, x64)).not.toContain('…');
		expect(staticAsserts(analyse('struct { char c; double d; } *p;', 'x64').layout, x64)).toBe('');
		const rows = compareTargets(FIXTURES[0].src);
		expect(rows.map((r) => r.layout?.size)).toEqual(ids.map((id) => FIXTURES[0][id]?.[0]));
		const mixed = compareTargets('struct s { char c; _Alignas(4) double d; };');
		expect(mixed.map((r) => !!r.layout)).toEqual(ids.map((id) => id === 'i386'));
		expect(compareTargets('struct {').every((r) => r.error)).toBe(true);
	});

	test('unsupported or invalid input gets a message with its line and column', () => {
		const cases: [string, RegExp, number, number][] = [
			['struct s {\n  int flags : 3;\n};', /Bit-fields are not supported/, 2, 13],
			['struct s {\n  u32 x;\n};', /Unknown type "u32"/, 2, 3],
			['struct s { int x }', /Expected a ";" after the member but found "}"/, 1, 18],
			['enum e { A };', /Enums are not supported/, 1, 1],
			['struct s { struct t x; };', /struct t is not defined before this point/, 1, 21],
			['struct s { struct s self; };', /struct s is not defined before this point/, 1, 21],
			['#define N 4\nstruct s { int a[N]; };', /Macros are not expanded/, 1, 1],
			['struct s { int a[N]; };', /Array sizes must be plain numbers/, 1, 18],
			['struct s { char c[]; int x; };', /Only the last member can be a flexible array/, 1, 17],
			['struct s { char c[]; };', /at least one other member/, 1, 17],
			['struct s { };', /empty struct/, 1, 1],
			['struct s { int a; int a; };', /Duplicate member "a"/, 1, 23],
			['struct s { _Alignas(3) int a; };', /power of two/, 1, 21],
			['struct s { void v; };', /void, which has no size/, 1, 17],
			['#pragma pack(3)\nstruct s { int a; };', /takes 1, 2, 4, 8 or 16/, 1, 1],
			['#pragma pack(pop)\nstruct s { int a; };', /without a matching push/, 1, 1],
			['struct __attribute__((aligned(8))) s { int a; };', /Only the packed attribute/, 1, 23],
			['struct s { long short x; };', /"long short" is not a C type/, 1, 12],
			['struct s { int a; };\nstruct s { int b; };', /defined twice/, 2, 1],
			['struct s { int a[0]; };', /zero-length array/, 1, 18],
			['int x;', /Expected a struct, union or typedef/, 1, 1],
			['', /Paste a struct or union definition/, 0, 0],
			['#if 0\nstruct a { int x; };\n#endif\nstruct s { int a; };', /Conditional compilation \(#if\)/, 1, 1],
			[
				'#ifdef _WIN32\nstruct s { int a; };\n#else\nstruct s { long a; };\n#endif',
				/\(#ifdef\) is not evaluated/,
				1,
				1
			],
			['#ifndef S_H\n#define S_H\nstruct s { int a; };', /no matching #endif/, 1, 1],
			['struct s { int a; };\n#endif', /#endif without a matching #ifndef/, 2, 1],
			['struct s { int a; struct { int a; }; };', /Duplicate member "a": the anonymous struct has one too/, 1, 19],
			['struct s { union { int a; struct { char b; }; }; int b; };', /Duplicate member "b"/, 1, 54],
			['struct s { char c[08]; };', /"08" is not a valid octal number/, 1, 19],
			['struct s { int \u{1F600}; };', /Unexpected character "\u{1F600}"/u, 1, 16]
		];
		for (const [src, message, line, column] of cases) {
			const e = errorOf(src);
			expect(e, src).not.toBeNull();
			expect(e?.message, src).toMatch(message);
			expect([e?.line, e?.column], src).toEqual([line, column]);
			if (line) expect(e?.message).toMatch(new RegExp(`^Line ${line}, column ${column}: `));
		}
		// _Alignas below the natural alignment depends on the target.
		expect(errorOf('struct s { char c; _Alignas(4) double d; };', 'x64')?.message).toMatch(/asks for less than/);
		expect(errorOf('struct s { char c; _Alignas(4) double d; };', 'i386')).toBeNull();
		expect(errorOf('x'.repeat(5000))?.message).toMatch(/more than 4000 characters/);
		// A record the main struct does not use is still checked, as a compiler would.
		expect(errorOf('struct a { _Alignas(1) int x; };\nstruct b { char c; };')?.message).toMatch(
			/^Line 1, column 28: _Alignas\(1\) asks for less/
		);
		expect(compareTargets('struct a { _Alignas(1) int x; };\nstruct b { char c; };').every((r) => r.error)).toBe(true);
		// An include guard is read straight through.
		expect(errorOf('#ifndef S_H\n#define S_H\nstruct s { int a; };\n#endif')).toBeNull();
		expect(errorOf('struct s { char c[010]; };')).toBeNull();
	});

	test('padding is counted exactly however large the struct is', () => {
		// Gaps far apart and big arrays: the totals come from arithmetic, not from a
		// byte map, so they hold beyond any drawing limit.
		const cases: [string, number, number, number][] = [
			// source, size, padding at this level, padding inside members
			['struct s { char c; double d; char big[70000]; };', 70016, 7, 0],
			['struct s { char big[65536]; char c; double d; };', 65552, 7, 0],
			['struct h { char c; double d[100000]; };', 800008, 7, 0],
			['struct a { char c; int i; };\nstruct s { struct a x[100000]; char z; };', 800004, 3, 300000]
		];
		for (const [src, size, padding, inner] of cases) {
			const { layout } = analyse(src, 'x64');
			expect([layout.size, layout.padding, layout.innerPadding, layout.wasted], src).toEqual([
				size,
				padding,
				inner,
				padding + inner
			]);
			expect(layout.wastedPercent).toBe(Math.round(((padding + inner) / size) * 1000) / 10);
		}
		// The drawing still knows where the first gaps are.
		const big = analyse('struct a { char c; int i; };\nstruct s { struct a x[100000]; char z; };', 'x64').layout;
		expect(paddingMask(big.gaps, 16)).toEqual([0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0].map(Boolean));
		// A union counts the bytes no member uses.
		const u = analyse('struct a { char c; int i; };\nunion u { struct a x[2]; char z[3]; };', 'x64').layout;
		expect([u.size, u.wasted]).toEqual([16, 4]);
		expect(paddingMask(u.gaps, 16)).toEqual([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0].map(Boolean));
	});

	test('hostile input stays quick', () => {
		const src = `struct b { ${Array.from({ length: 240 }, (_, i) => `char m${i}[65536];`).join('')} };`;
		expect(src.length).toBeLessThanOrEqual(4000);
		const start = Date.now();
		analyse(src, 'x64');
		compareTargets(src);
		expect(Date.now() - start).toBeLessThan(500);
	});

	test('the reordered code keeps what it needs and lays out the same again', () => {
		// Each source is reordered on every target, then the reordered whole input
		// is parsed and laid out again: it must give the promised layout. The
		// outputs were also compiled with clang 18 for x86_64 and i386, which
		// accepted every one and agreed on the sizes.
		const sources = [
			'struct point { short x, y; };\nstruct s { char a; double d; struct point p; char b; };',
			'typedef unsigned char u8;\nstruct s { u8 a; double d; u8 b; };',
			'struct outer { char c; struct p { double d; } x, y; char z; };',
			'struct outer { struct inner { int v; }; char c; struct inner more; char e; double d; };',
			'struct outer { char c; struct inner { long double v; } *ptr; struct inner val; };',
			'struct o { char c; struct { char q; struct t { double z; } tt; } anon; double d; };',
			'#pragma pack(push, 2)\nstruct o { char c; struct t { char a; double d; } x; int i; };\n#pragma pack(pop)',
			'struct o { char c; const _Alignas(16) struct __attribute__((packed)) t { char a; double d; } x; int i; union { char u; long l; }; };',
			'typedef struct node { char c; struct node *next; struct kid { short k; } *kids, one; } node_t;\nstruct after { int z; };'
		];
		for (const src of sources)
			for (const target of TARGETS) {
				const a = analyse(src, target.id);
				const r = a.reordered;
				expect(r, src).not.toBeNull();
				if (!r) continue;
				const again = analyse(r.source, target.id);
				expect([again.layout.size, again.layout.members.map((m) => m.offset)], `${target.id}: ${r.source}`).toEqual([
					r.layout.size,
					r.layout.members.map((m) => m.offset)
				]);
				// A tag is defined once, ahead of any member that uses it.
				for (const tag of src.match(/struct \w+ \{/g) ?? []) expect(r.source.split(tag).length - 1, r.source).toBe(1);
			}
		const nested = analyse(sources[2], 'x64').reordered;
		expect(nested?.code).toBe(
			'struct p {\n    double d;\n};\n\nstruct outer {\n    struct p x;\n    struct p y;\n    char c;\n    char z;\n};'
		);
		// Only the main definition is swapped; the rest of the input stays as written.
		const multi = analyse(sources[0], 'x64').reordered;
		expect(multi?.source).toBe(
			'struct point { short x, y; };\nstruct s {\n    double d;\n    struct point p;\n    char a;\n    char b;\n};'
		);
		// The copy carries the pragma it needs; the swapped source already has it.
		const packed = analyse(sources[6], 'x64').reordered;
		expect(packed?.code.startsWith('#pragma pack(push, 2)\n')).toBe(true);
		expect(packed?.source.match(/#pragma/g)).toHaveLength(2);
	});

	test('comments, includes and C spellings are accepted', () => {
		const src = `#include <stdint.h>
// a comment
/* a block
   comment */
typedef unsigned char u8;
struct s {
	const char *name; /* trailing */
	unsigned long int a, *b, c[2];
	signed d;
	u8 e;
	alignas(16) uint8_t f;
};`;
		const a = analyse(src, 'x64');
		expect(a.layout.members.map((m) => m.label)).toEqual(['name', 'a', 'b', 'c', 'd', 'e', 'f']);
		expect(a.layout.members.map((m) => m.type)).toEqual([
			'char *',
			'unsigned long int',
			'unsigned long int *',
			'unsigned long int [2]',
			'signed',
			'u8',
			'uint8_t'
		]);
		expect(a.layout.members[6].offset).toBe(48);
		expect(a.layout.members[1].code).toBe('unsigned long int a;');
		expect(a.layout.members[2].code).toBe('unsigned long int *b;');
	});
});

test.describe('the struct-padding-calculator page', () => {
	const answer = (page: Page) => page.locator('.answer-value');

	test('the prerendered HTML already shows the default layout', async ({ page }) => {
		const html = await (await page.request.get('/struct-padding-calculator')).text();
		expect(html).toContain('Struct padding calculator');
		expect(html).toMatch(/32 bytes<\/span>/);
		expect(html).toContain('16 bytes of padding');
		expect(html).toContain('Reordered: 16 bytes');
		expect(html).toContain('offset 1 is not a multiple of 8, so 7 bytes of padding go in first');
	});

	test('editing the struct and switching target relayout it', async ({ page }) => {
		await page.goto('/struct-padding-calculator');
		await page.waitForLoadState('networkidle');
		await page.fill('#struct-source', 'struct s { char c; long l; };');
		await expect(answer(page)).toHaveText('16 bytes');
		await page.selectOption('#target', 'win64');
		await expect(answer(page)).toHaveText('8 bytes');
		await expect(page.locator('.members tbody tr')).toHaveCount(3);
		await expect(page.locator('.members tbody tr').nth(1).locator('td').nth(1)).toHaveText('4');

		await page.fill('#struct-source', 'struct s {\n  int flags : 3;\n};');
		await expect(page.locator('[role="alert"]')).toContainText('Line 2, column 13: Bit-fields are not supported');
		await expect(page.locator('#struct-source')).toHaveAttribute('aria-invalid', 'true');

		// The results stay on screen, dimmed, and out of reach of the keyboard.
		await expect(page.locator('.results')).toHaveAttribute('inert', '');

		await page.getByRole('button', { name: 'Tagged union' }).click();
		await expect(page.locator('[role="alert"]')).toHaveCount(0);
		await expect(page.locator('.results')).not.toHaveAttribute('inert', '');
		// Every chip sets its own target: back on x86-64 Linux.
		await expect(page.locator('#target')).toHaveValue('x64');
		await expect(answer(page)).toHaveText('24 bytes');
		// The comparison table switches target too.
		await page.getByRole('button', { name: '32-bit x86 Linux' }).click();
		await expect(page.locator('#target')).toHaveValue('i386');
		await expect(answer(page)).toHaveText('16 bytes');
	});

	test('the reordered version can be laid out in one click', async ({ page }) => {
		await page.goto('/struct-padding-calculator');
		await page.waitForLoadState('networkidle');
		await page.getByRole('button', { name: 'Lay out this version' }).click();
		await expect(answer(page)).toHaveText('16 bytes');
		await expect(page.locator('#struct-source')).toHaveValue(/double value;\n {4}int count;/);
	});

	test('laying out the reordered version keeps the structs it uses', async ({ page }) => {
		await page.goto('/struct-padding-calculator');
		await page.waitForLoadState('networkidle');
		await page.fill(
			'#struct-source',
			'typedef unsigned char u8;\nstruct point { short x, y; };\nstruct s { u8 a; double d; struct point p; u8 b; };'
		);
		await expect(answer(page)).toHaveText('24 bytes');
		await page.getByRole('button', { name: 'Lay out this version' }).click();
		await expect(answer(page)).toHaveText('16 bytes');
		await expect(page.locator('[role="alert"]')).toHaveCount(0);
		await expect(page.locator('#struct-source')).toHaveValue(
			'typedef unsigned char u8;\nstruct point { short x, y; };\nstruct s {\n    double d;\n    struct point p;\n    u8 a;\n    u8 b;\n};'
		);
	});

	test('a link to an invalid struct shows the error, not the default layout', async ({ page }) => {
		await page.goto('/struct-padding-calculator?c=' + encodeURIComponent('struct s { int a : 3; };'));
		await page.waitForLoadState('networkidle');
		await expect(page.locator('#source-error')).toContainText('Bit-fields are not supported');
		await expect(page.locator('.results')).toHaveCount(0);
		await expect(page.locator('.empty-state')).toBeVisible();
		// An empty field is kept in the link too.
		await page.fill('#struct-source', '');
		await expect(page).toHaveURL(/\?c=\+$/);
		await page.reload();
		await page.waitForLoadState('networkidle');
		await expect(page.locator('#source-error')).toContainText('Paste a struct or union definition');
	});

	test('a shared link round trips exactly', async ({ page }) => {
		const src = '#pragma pack(2)\nstruct s { char c; double d; };';
		await page.goto('/struct-padding-calculator');
		await page.waitForLoadState('networkidle');
		await page.fill('#struct-source', src);
		await page.selectOption('#target', 'arm32');
		await expect(answer(page)).toHaveText('10 bytes');
		const url = page.url();
		expect(url).toContain('t=arm32');
		await page.goto(url);
		await page.waitForLoadState('networkidle');
		await expect(page.locator('#struct-source')).toHaveValue(src);
		await expect(page.locator('#target')).toHaveValue('arm32');
		await expect(answer(page)).toHaveText('10 bytes');
		// Bad values in the query string are ignored, not trusted.
		await page.goto('/struct-padding-calculator?t=vax');
		await page.waitForLoadState('networkidle');
		await expect(page.locator('#target')).toHaveValue('x64');
	});

	test('the FAQ markup matches the visible answers', async ({ page }) => {
		await page.goto('/struct-padding-calculator');
		const blocks = await page.locator('script[type="application/ld+json"]').allTextContents();
		const graph = blocks.map((t) => JSON.parse(t)).flatMap((b) => b['@graph'] ?? [b]);
		const webPage = graph.find((n: { '@id'?: string }) => n['@id']?.endsWith('/struct-padding-calculator#webpage'));
		const visible = await page.locator('.faq details').evaluateAll((ds) =>
			ds.map((d) => ({
				q: d.querySelector('summary')?.textContent?.trim(),
				a: d.querySelector('p')?.textContent?.trim()
			}))
		);
		expect(visible.length).toBeGreaterThanOrEqual(4);
		expect(
			webPage.mainEntity.map((q: { name: string; acceptedAnswer: { text: string } }) => ({
				q: q.name,
				a: q.acceptedAnswer.text
			}))
		).toEqual(visible);
	});
});
