<script lang="ts">
	import { SITE } from '$lib/site';
	import ContentPage from '$lib/ContentPage.svelte';
	import { modifiedFields } from '$lib/lastmod';
	import {
		parseRadix,
		placeValueSteps,
		divisionSteps,
		toRadix,
		groupDigits,
		groupDecimal,
		hexDigitTable,
		superscript,
		RadixError,
		MAX_DIGITS
	} from '$lib/radix';
	import { readUrl, syncUrl, safeText, safeOption } from '$lib/urlState';
	import ShareLink from '$lib/ShareLink.svelte';
	import { onMount } from 'svelte';

	type Direction = 'hex' | 'dec';
	const DEFAULTS = { v: 'BEEF', from: 'hex' };
	onMount(() => {
		const p = readUrl();
		input = safeText(p.v, MAX_DIGITS + 10) ?? input;
		from = safeOption(p.from, ['hex', 'dec'] as const) ?? from;
	});
	$: syncUrl({ v: input, from }, DEFAULTS);

	let input = DEFAULTS.v;
	let from: Direction = 'hex';

	// Runs at build time too, so the page ships with a real worked conversion.
	let value = 0n;
	let digits = '';
	let error = '';
	$: {
		try {
			const parsed = parseRadix(input, from === 'hex' ? 16 : 10);
			value = parsed.value;
			digits = parsed.digits.replace(/^0+(?=.)/, '');
			error = '';
		} catch (e) {
			error = e instanceof RadixError ? e.message : 'That is not a number';
		}
	}
	$: hex = toRadix(value, 16);
	$: places = placeValueSteps(from === 'hex' ? digits : hex, 16);
	$: division = divisionSteps(value, 16);

	/** Switching direction carries the answer across, so the reverse is one click away. */
	function swap() {
		if (!error) input = from === 'hex' ? value.toString() : hex;
		from = from === 'hex' ? 'dec' : 'hex';
	}

	function tryValue(v: string, direction: Direction) {
		from = direction;
		input = v;
		const field = document.getElementById('value');
		field?.scrollIntoView({ behavior: 'smooth', block: 'center' });
		field?.focus({ preventScroll: true });
	}

	const examples: { label: string; v: string; from: Direction }[] = [
		{ label: 'FF', v: 'FF', from: 'hex' },
		{ label: '#1E90FF', v: '#1E90FF', from: 'hex' },
		{ label: '7FFFFFFF', v: '7FFFFFFF', from: 'hex' },
		{ label: '0xDEADBEEF', v: '0xDEADBEEF', from: 'hex' },
		{ label: '255 to hex', v: '255', from: 'dec' },
		{ label: '1000 to hex', v: '1000', from: 'dec' },
		{ label: '65535 to hex', v: '65535', from: 'dec' }
	];

	const dec = (n: bigint) => groupDecimal(n.toString());
	/** A sum written out: 11×16³ + 14×16² + … */
	const termText = (t: { value: number; power: number }) => `${t.value}×16${superscript(t.power)}`;

	// Worked examples, generated by the same engine as the converter.
	const ff = placeValueSteps('FF', 16);
	const worked1 = placeValueSteps('1A3', 16);
	const worked2 = divisionSteps(1000n, 16);
	const colour = { r: parseRadix('1E', 16).value, g: parseRadix('90', 16).value, b: parseRadix('FF', 16).value };
	const powers = Array.from({ length: 9 }, (_, n) => ({ n, value: 16n ** BigInt(n) }));

	const faqs = [
		{
			q: 'What is FF in decimal?',
			a: `FF is ${ff.total}. The left F is worth ${ff.terms[0].value} × 16 = ${ff.terms[0].product} and the right F is worth ${ff.terms[1].value} × 1 = ${ff.terms[1].product}, and ${ff.terms[0].product} + ${ff.terms[1].product} = ${ff.total}. It is the largest value one byte can hold, which is why it turns up in colour codes and masks.`
		},
		{
			q: 'How do I convert hex to decimal by hand?',
			a: 'Number the digits from the right starting at 0. Multiply each digit by 16 to the power of its position, using A = 10, B = 11, C = 12, D = 13, E = 14 and F = 15, then add the results. For 1A3 that is 1×256 + 10×16 + 3×1 = 419.'
		},
		{
			q: 'How do I convert decimal to hex?',
			a: 'Divide the number by 16 and write down the remainder, then divide the quotient by 16 again, and keep going until the quotient is 0. Write each remainder as a hex digit (10 is A, 15 is F) and read them from the last one to the first. 1000 gives remainders 8, 14 and 3, so it is 3E8.'
		},
		{
			q: 'What does 0x mean in front of a number?',
			a: 'It marks the number as hexadecimal in C, JavaScript, Python and most other languages, so 0x10 is sixteen and not ten. CSS writes a # instead for colours, and some assemblers use a trailing h or a leading $. The converter accepts 0x, # and $ and ignores them.'
		},
		{
			q: 'How big a number can this convert?',
			a: `Up to ${MAX_DIGITS} digits of either base, which is 256 bits in hex. The arithmetic uses whole numbers of any size, so nothing is rounded the way it would be in a spreadsheet past about 15 digits. Negative numbers and fractions are not converted here; a negative number needs a fixed width, which the two's complement page covers.`
		},
		{
			q: 'Why is hexadecimal base 16?',
			a: 'Because 16 is 2 to the power 4, so one hex digit stands for exactly four bits. That makes converting between hex and binary a matter of looking up each digit, while still writing a byte in two characters instead of eight.'
		}
	];

	const page = {
		title: 'Hex to Decimal Converter (and Decimal to Hex), With Steps',
		description:
			'Convert hex to decimal and decimal to hex with every step shown: place values for hex to decimal, repeated division by 16 for decimal to hex.',
		url: `${SITE}/hex-to-decimal`,
		image: `${SITE}/og/hex-to-decimal.png`,
		imageAlt: 'LogicGates.org: hex to decimal converter with steps'
	};

	const jsonLd = `<script type="application/ld+json">${JSON.stringify({
		'@context': 'https://schema.org',
		'@graph': [
			{
				'@type': ['WebPage', 'FAQPage'],
				'@id': `${page.url}#webpage`,
				url: page.url,
				name: page.title,
				description: page.description,
				isPartOf: { '@id': `${SITE}/#website` },
				breadcrumb: { '@id': `${page.url}#breadcrumb` },
				inLanguage: 'en',
				...modifiedFields(page.url),
				mainEntity: faqs.map((f) => ({
					'@type': 'Question',
					name: f.q,
					acceptedAnswer: { '@type': 'Answer', text: f.a }
				}))
			},
			{
				'@type': 'BreadcrumbList',
				'@id': `${page.url}#breadcrumb`,
				itemListElement: [
					{ '@type': 'ListItem', position: 1, name: 'LogicGates.org', item: `${SITE}/` },
					{ '@type': 'ListItem', position: 2, name: 'Tools', item: `${SITE}/tools` },
					{ '@type': 'ListItem', position: 3, name: 'Hex to decimal converter' }
				]
			}
		]
	})}${'<'}/script>`;
</script>

<svelte:head>
	<title>{page.title}</title>
	<meta name="description" content={page.description} />
	<link rel="canonical" href={page.url} />
	<meta name="author" content="Sem" />
	<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1" />
	<meta property="og:type" content="website" />
	<meta property="og:site_name" content="LogicGates.org" />
	<meta property="og:locale" content="en" />
	<meta property="og:title" content={page.title} />
	<meta property="og:description" content={page.description} />
	<meta property="og:url" content={page.url} />
	<meta property="og:image" content={page.image} />
	<meta property="og:image:alt" content={page.imageAlt} />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content={page.title} />
	<meta name="twitter:description" content={page.description} />
	<meta name="twitter:image" content={page.image} />
	{@html jsonLd}
</svelte:head>

<ContentPage
	related={[
		{ href: '/hex-to-binary', label: 'Hex to binary converter' },
		{ href: '/hex-calculator', label: 'Hex calculator' },
		{ href: '/binary-converter', label: 'Binary converter' },
		{ href: '/twos-complement', label: "Two's complement" },
		{ href: '/tools', label: 'All tools' }
	]}
>
	<section class="intro">
		<h1>Hex to decimal converter</h1>
		<p class="lede">
			Type a hexadecimal number to get its decimal value, or switch direction for decimal to hex. Every conversion shows
			its working: place values one way, repeated division by 16 the other.
		</p>

		<div class="card tool">
			<div class="direction" role="group" aria-label="Direction">
				<button
					type="button"
					class:active={from === 'hex'}
					aria-pressed={from === 'hex'}
					on:click={() => from !== 'hex' && swap()}>Hex to decimal</button
				>
				<button
					type="button"
					class:active={from === 'dec'}
					aria-pressed={from === 'dec'}
					on:click={() => from !== 'dec' && swap()}>Decimal to hex</button
				>
			</div>

			<label class="field" for="value">{from === 'hex' ? 'Hex number' : 'Decimal number'}</label>
			<input
				id="value"
				class="value-input"
				type="text"
				bind:value={input}
				spellcheck="false"
				autocomplete="off"
				autocapitalize="off"
				inputmode={from === 'dec' ? 'numeric' : 'text'}
				aria-invalid={error ? 'true' : 'false'}
				aria-describedby="value-help"
			/>
			{#if error}
				<p class="error" role="alert">{error}</p>
			{/if}
			<p class="field-help" id="value-help">
				{#if from === 'hex'}
					Digits 0 to 9 and A to F, upper or lower case. A leading 0x, # or $ is ignored, and so are spaces.
				{:else}
					A whole number of zero or more, up to {MAX_DIGITS} digits.
				{/if}
			</p>

			<div class="chips">
				{#each examples as example}
					<button type="button" class="chip-btn" on:click={() => tryValue(example.v, example.from)}>
						{example.label}
					</button>
				{/each}
			</div>

			<div class="results" class:stale={!!error} aria-hidden={error ? 'true' : 'false'}>
				<div class="answer" role={error ? undefined : 'status'}>
					<span class="answer-label">{from === 'hex' ? 'Decimal' : 'Hex'}</span>
					<span class="answer-value mono">{from === 'hex' ? dec(value) : hex}</span>
					<span class="answer-also"
						>{from === 'hex' ? `${hex} in hex` : `${dec(value)} in decimal`} is
						<span class="mono">{groupDigits(value.toString(2), 4)}</span> in binary</span
					>
				</div>

				{#if from === 'hex'}
					<h3 class="working-title">Working: each digit times its place value</h3>
					<div class="table-wrap scroll-box">
						<table class="data-table steps">
							<thead>
								<tr>
									<th scope="col">Digit</th>
									<th scope="col">Value</th>
									<th scope="col">Place</th>
									<th scope="col" class="num">Place value</th>
									<th scope="col" class="num">Digit × place</th>
								</tr>
							</thead>
							<tbody>
								{#each places.terms as term}
									<tr>
										<td class="mono strong">{term.digit}</td>
										<td class="mono">{term.value}</td>
										<td class="mono">16{superscript(term.power)}</td>
										<td class="mono num">{dec(term.place)}</td>
										<td class="mono num">{dec(term.product)}</td>
									</tr>
								{/each}
								<tr class="total">
									<th scope="row" colspan="4">Sum</th>
									<td class="mono num strong">{dec(places.total)}</td>
								</tr>
							</tbody>
						</table>
					</div>
					{#if places.terms.length <= 8}
						<p class="equation mono">
							{places.terms.map(termText).join(' + ')}<br />= {places.terms.map((t) => dec(t.product)).join(' + ')}<br
							/>= {dec(places.total)}
						</p>
					{/if}
				{:else}
					<h3 class="working-title">Working: divide by 16, keep the remainders</h3>
					<div class="table-wrap scroll-box">
						<table class="data-table steps">
							<thead>
								<tr>
									<th scope="col" class="num">Number</th>
									<th scope="col" class="num">÷ 16</th>
									<th scope="col">Remainder</th>
									<th scope="col">Hex digit</th>
								</tr>
							</thead>
							<tbody>
								{#each division.steps as step}
									<tr>
										<td class="mono num">{dec(step.dividend)}</td>
										<td class="mono num">{dec(step.quotient)}</td>
										<td class="mono">{step.remainder}</td>
										<td class="mono strong">{step.digit}</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
					<p class="equation">
						Read the hex digits from the bottom up: <span class="mono strong">{division.result}</span>. The first
						remainder is the last digit, because it is the part left over after taking out every whole 16.
					</p>
				{/if}
			</div>
			<p class="share-row"><ShareLink what="this conversion" /></p>
		</div>
	</section>

	<section id="what-is-hex">
		<h2>What hexadecimal is</h2>
		<p>
			Hexadecimal, or hex, is base 16. Decimal runs out of digits at 9 and carries into the tens column; hex keeps going
			with six letters, A to F for ten to fifteen, and only carries at sixteen. So 10 in hex is sixteen, 100 is 16 × 16
			= 256, and FF is the largest two digit value, 255.
		</p>
		<div class="table-wrap">
			<table class="data-table digits">
				<caption>The sixteen hex digits</caption>
				<thead>
					<tr>
						<th scope="col">Hex</th>
						<th scope="col">Decimal</th>
						<th scope="col">Binary</th>
						<th scope="col" class="gap">Hex</th>
						<th scope="col">Decimal</th>
						<th scope="col">Binary</th>
					</tr>
				</thead>
				<tbody>
					{#each hexDigitTable.slice(0, 8) as row, i}
						{@const other = hexDigitTable[i + 8]}
						<tr>
							<td class="mono strong">{row.hex}</td>
							<td class="mono">{row.decimal}</td>
							<td class="mono">{row.binary}</td>
							<td class="mono strong gap">{other.hex}</td>
							<td class="mono">{other.decimal}</td>
							<td class="mono">{other.binary}</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
	</section>

	<section id="why">
		<h2>Why programmers use hex</h2>
		<ul class="points">
			<li>
				<strong>Four bits per digit.</strong> Sixteen is 2<sup>4</sup>, so each hex digit is exactly one group of four
				bits, a nibble. Converting to binary is a lookup, digit by digit, with no arithmetic; the
				<a href="/hex-to-binary">hex to binary converter</a> shows it.
			</li>
			<li>
				<strong>A byte is two digits.</strong> Eight bits always fit in 00 to FF, so memory dumps, network packets and file
				formats line up in neat pairs. The same byte in decimal takes one to three digits and does not line up.
			</li>
			<li>
				<strong>Colours.</strong> A CSS colour such as
				<span class="swatch" style="background:#1E90FF" aria-hidden="true" />
				<span class="mono">#1E90FF</span> is three bytes: red 1E = {colour.r}, green 90 = {colour.g} and blue FF =
				{colour.b}.
			</li>
			<li>
				<strong>Memory addresses and masks.</strong> An address like 0x7FFF0010 or a mask like 0xFF00 is easier to read and
				check in hex, because you can see which bits are set without converting anything.
			</li>
		</ul>
	</section>

	<section id="examples">
		<h2>Worked examples</h2>
		<div class="worked-grid">
			<div class="card worked">
				<h3>1A3 to decimal</h3>
				<p class="mono small">
					{#each worked1.terms as t, i}{i ? ' + ' : ''}{t.digit}×16{superscript(t.power)}{/each}<br />
					= {worked1.terms.map((t) => `${t.value}×${t.place}`).join(' + ')}<br />
					= {worked1.terms.map((t) => t.product).join(' + ')}<br />
					= <strong>{worked1.total}</strong>
				</p>
				<p class="small">
					A is 10, so the middle digit is worth 10 × 16. <a
						href="/hex-to-decimal?v=1A3"
						on:click|preventDefault={() => tryValue('1A3', 'hex')}>Try it</a
					>
				</p>
			</div>
			<div class="card worked">
				<h3>1000 to hex</h3>
				<p class="mono small">
					{#each worked2.steps as s}{s.dividend} ÷ 16 = {s.quotient} remainder {s.remainder}{s.remainder > 9
							? ` (${s.digit})`
							: ''}<br />{/each}
				</p>
				<p class="small">
					Read the remainders upwards: <strong class="mono">{worked2.result}</strong>.
					<a href="/hex-to-decimal?v=1000&amp;from=dec" on:click|preventDefault={() => tryValue('1000', 'dec')}
						>Try it</a
					>
				</p>
			</div>
		</div>
		<p class="section-intro">
			Powers of 16 are the place values, the way powers of 10 are in decimal. The first few are worth knowing:
		</p>
		<div class="table-wrap">
			<table class="data-table powers">
				<thead>
					<tr><th scope="col">Power</th><th scope="col" class="num">Value</th><th scope="col">In hex</th></tr>
				</thead>
				<tbody>
					{#each powers as p}
						<tr>
							<td class="mono">16{superscript(p.n)}</td>
							<td class="mono num">{dec(p.value)}</td>
							<td class="mono">1{'0'.repeat(p.n)}</td>
						</tr>
					{/each}
				</tbody>
			</table>
		</div>
		<p class="reducer">
			To add, subtract or multiply hex numbers directly, with carries shown, use the <a href="/hex-calculator"
				>hex calculator</a
			>. For signed values in a fixed number of bits, see <a href="/twos-complement">two's complement</a> and the
			<a href="/binary-converter">binary converter</a>.
		</p>
	</section>

	<section class="faq">
		<h2>Questions</h2>
		{#each faqs as faq, i}
			<details open={i === 0}>
				<summary>{faq.q}</summary>
				<p>{faq.a}</p>
			</details>
		{/each}
	</section>
</ContentPage>

<style>
	.intro {
		padding-top: 64px;
	}

	.tool {
		padding: 1.1rem 1.2rem 1.3rem;
		margin-bottom: 1rem;
	}

	.direction {
		display: inline-flex;
		flex-wrap: wrap;
		gap: 4px;
		margin-bottom: 0.9rem;
	}

	.direction button {
		background: #0d0d0f;
		border: 1px solid rgba(255, 255, 255, 0.4);
		border-radius: 3px;
		color: #ddd;
		font-size: 0.9rem;
		padding: 0.4rem 0.9rem;
		cursor: pointer;
	}

	.direction button.active {
		background-color: #372;
		border-color: #5db65d;
		color: #fff;
	}

	.field {
		display: block;
		font-size: 0.85rem;
		color: #ddd;
		margin-bottom: 0.35rem;
	}

	.value-input {
		width: 100%;
		box-sizing: border-box;
		background-color: #0d0d0f;
		border: 1px solid rgba(255, 255, 255, 0.4);
		border-radius: 3px;
		color: #fff;
		font: 1.15rem ui-monospace, SFMono-Regular, Menlo, monospace;
		padding: 0.6rem 0.7rem;
	}

	.value-input:focus {
		outline: none;
		border-color: #5db65d;
	}

	.value-input[aria-invalid='true'] {
		border-color: #f66;
	}

	.field-help {
		color: #999;
		font-size: 0.8rem;
		margin: 0.45rem 0 0.7rem;
	}

	.error {
		color: #f66;
		font-size: 0.9rem;
		margin: 0.4rem 0 0;
	}

	.chips {
		display: flex;
		flex-wrap: wrap;
		gap: 6px;
		margin-bottom: 1rem;
	}

	.chip-btn {
		background: #0d0d0f;
		border: 1px solid rgba(255, 255, 255, 0.4);
		border-radius: 3px;
		color: #ddd;
		font: 0.8rem ui-monospace, SFMono-Regular, Menlo, monospace;
		padding: 0.25rem 0.6rem;
		cursor: pointer;
	}

	.chip-btn:hover {
		border-color: #5db65d;
		color: #fff;
	}

	.results {
		border-top: 1px solid rgba(255, 255, 255, 0.12);
		padding-top: 1rem;
	}

	.results.stale {
		opacity: 0.35;
		pointer-events: none;
	}

	.answer {
		background: #0d0d0f;
		border: 1px solid rgba(93, 182, 93, 0.5);
		border-radius: 3px;
		padding: 0.6rem 0.8rem;
	}

	.answer-label {
		color: #999;
		display: block;
		font-size: 0.72rem;
		letter-spacing: 0.05em;
		text-transform: uppercase;
	}

	.answer-value {
		color: #8ede8e;
		display: block;
		font-size: 1.6rem;
		overflow-wrap: anywhere;
	}

	.answer-also {
		color: #bbb;
		display: block;
		font-size: 0.85rem;
		margin-top: 0.2rem;
		overflow-wrap: anywhere;
	}

	.working-title {
		margin-top: 1.1rem !important;
	}

	.scroll-box {
		max-height: 420px;
		overflow: auto;
	}

	.steps td,
	.steps th {
		white-space: nowrap;
	}

	.num {
		text-align: right !important;
	}

	.data-table td.strong,
	.strong {
		color: #8ede8e;
		font-weight: 700;
	}

	.steps tr.total th,
	.steps tr.total td {
		border-top: 2px solid rgba(255, 255, 255, 0.4);
		color: #fff;
	}

	.equation {
		color: #ccc;
		font-size: 0.92rem;
		margin: 0.7rem 0 0;
		overflow-wrap: anywhere;
	}

	.share-row {
		display: flex;
		align-items: center;
		flex-wrap: wrap;
		gap: 0.6rem;
		margin: 1rem 0 0;
	}

	.digits caption {
		text-align: left;
		color: #bbb;
		font-size: 0.85rem;
		padding-bottom: 0.4rem;
	}

	.digits .gap {
		border-left: 1px solid rgba(255, 255, 255, 0.25);
	}

	.points {
		color: #ddd;
		max-width: 720px;
		padding-left: 1.25rem;
	}

	.points li {
		margin-bottom: 0.6rem;
	}

	.points strong {
		color: #fff;
	}

	.swatch {
		display: inline-block;
		width: 0.9em;
		height: 0.9em;
		border-radius: 2px;
		vertical-align: -0.1em;
		border: 1px solid rgba(255, 255, 255, 0.4);
	}

	.worked-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
		gap: 12px;
		margin-bottom: 1.2rem;
	}

	.worked {
		padding: 0.9rem 1rem;
	}

	.worked h3 {
		color: #fff;
	}

	.small {
		font-size: 0.9rem;
		margin: 0.4rem 0 0;
		overflow-wrap: anywhere;
	}

	.worked strong {
		color: #8ede8e;
	}

	/* Both halves of the table fit a phone without scrolling. */
	@media (max-width: 560px) {
		.digits th,
		.digits td {
			padding-left: 0.45rem;
			padding-right: 0.45rem;
			font-size: 0.85rem;
		}
	}
</style>
