<script lang="ts">
	import { SITE } from '$lib/site';
	import ContentPage from '$lib/ContentPage.svelte';
	import { modifiedFields } from '$lib/lastmod';
	import {
		parseExpression,
		parseSystem,
		truthTable,
		truthTables,
		formatSystem,
		simplify,
		BooleanError,
		MAX_VARS,
		type SystemTable
	} from '$lib/boolean';
	import { truthTableToSvg, type Palette } from '$lib/exportSvg';
	import { downloadSvg, downloadPng, slugifyExpression } from '$lib/download';

	import { readUrl, syncUrl, safeText, safeOption, toolLink } from '$lib/urlState';
	import ShareLink from '$lib/ShareLink.svelte';
	import { onMount } from 'svelte';

	// Every setting lives in the query string, so a link reopens this exactly.
	const DEFAULTS = { expr: 'a & b | !c', palette: 'colour' };
	onMount(() => {
		const p = readUrl();
		expression = safeText(p.expr) ?? expression;
		palette = safeOption(p.palette, ['colour', 'mono'] as const) ?? palette;
	});
	$: syncUrl({ expr: expression, palette }, DEFAULTS);

	let expression = 'a & b | !c';
	let palette: Palette = 'colour';
	let exporting = '';

	// Runs during prerendering too, so the page ships with a real, crawlable
	// truth table rather than an empty widget.
	let table: SystemTable | null = null;
	let reading = '';
	let sops: { name: string; text: string; high: number }[] = [];
	let error = '';
	$: {
		try {
			// One expression, or several separated by semicolons: `sum = a ^ b; carry = a & b`.
			const outputs = parseSystem(expression);
			table = truthTables(outputs);
			reading = formatSystem(outputs, 'math');
			sops = table.outputs.map((o) => ({
				name: o.name,
				text: simplify({ variables: table!.variables, rows: o.rows }, 'math').text,
				high: o.rows.filter(Boolean).length
			}));
			error = '';
		} catch (e) {
			table = null;
			error = e instanceof BooleanError ? e.message : 'That expression did not parse';
		}
	}

	const asSvg = () => (table ? truthTableToSvg(table, { palette, caption: reading }) : '');

	const filename = (ext: string) => `${slugifyExpression(reading)}-truth-table.${ext}`;

	async function exportFile(kind: 'svg' | 'png') {
		if (!table) return;
		exporting = kind;
		try {
			if (kind === 'svg') downloadSvg(asSvg(), filename('svg'));
			else await downloadPng(asSvg(), filename('png'), 2);
		} finally {
			exporting = '';
		}
	}

	const examples = [
		{ label: 'De Morgan', value: '!(a & b)' },
		{ label: 'Absorption', value: 'a | (a & b)' },
		{ label: 'Majority of three', value: 'ab + bc + ac' },
		{ label: 'Four variables', value: '(a ^ b) & (c | !d)' },
		// Several outputs in one table, separated by semicolons.
		{ label: 'Half adder', value: 'sum = a ^ b; carry = a & b' },
		{ label: '1-bit comparator', value: 'lt = !a & b; eq = !(a ^ b); gt = a & !b' }
	];

	const halfAdderExpression = 'sum = a ^ b; carry = a & b';

	// Reference tables, generated by the same engine that powers the widget.
	const gateRef = [
		{ name: 'AND', expr: 'a & b', symbol: 'a ∧ b', note: 'high only when both inputs are high' },
		{ name: 'OR', expr: 'a | b', symbol: 'a ∨ b', note: 'high when either input is high' },
		{ name: 'XOR', expr: 'a ^ b', symbol: 'a ⊻ b', note: 'high when the inputs differ' },
		{ name: 'NAND', expr: '!(a & b)', symbol: '¬(a ∧ b)', note: 'the inverse of AND' },
		{ name: 'NOR', expr: '!(a | b)', symbol: '¬(a ∨ b)', note: 'the inverse of OR' },
		{ name: 'NOT', expr: '!a', symbol: '¬a', note: 'inverts its single input' }
	].map((gate) => ({ ...gate, table: truthTable(parseExpression(gate.expr)) }));

	// The classic worked example: one input pair, two outputs.
	const halfAdder = {
		sum: truthTable(parseExpression('a ^ b')),
		carry: truthTable(parseExpression('a & b'))
	};

	const faqs = [
		{
			q: 'How do I write the expression?',
			a: 'Use whichever notation you are used to. AND can be written as a·b, a&b, a∧b, a AND b or just ab; OR as a+b, a|b, a∨b or a OR b; NOT as !a, ~a, ¬a, a’ or NOT a; XOR as a^b, a⊻b or a XOR b. Brackets work as you would expect, and 0 and 1 are constants.'
		},
		{
			q: 'Can the table have more than one output?',
			a: 'Yes. Separate the expressions with semicolons and name each one, as in "sum = a ^ b; carry = a & b". The table gets one column per output, all over the same inputs, so the rows line up the way they would for a real circuit. The circuit diagram generator takes the same syntax and draws every output.'
		},
		{
			q: 'How many variables can it handle?',
			a: `Up to ${MAX_VARS}, which is a table of 256 rows. Single letters are variables, so "abc" means a AND b AND c.`
		},
		{
			q: 'How is the table ordered?',
			a: 'Rows count up in binary from all zeros to all ones, with the first variable as the most significant bit. That is the conventional ordering, so the table matches the one in your textbook.'
		},
		{
			q: 'Can I get a circuit out of a truth table?',
			a: 'Yes, in the simulator. Open Logic Nodes on an empty canvas and press ctrl+T (or cmd+T), fill in the output column, and it builds a working circuit of real gates that matches your table.'
		}
	];

	const page = {
		title: 'Truth Table Generator: Boolean Expression to Truth Table',
		description:
			'Type a boolean expression and get its truth table instantly. Supports AND, OR, NOT, XOR, NAND and NOR in any notation. Free, no signup, runs in your browser.',
		url: `${SITE}/truth-table-generator`,
		image: `${SITE}/og/truth-table-generator.png`,
		imageAlt: 'Logic Nodes: truth table generator'
	};

	const jsonLd = `<script type="application/ld+json">${JSON.stringify({
		'@context': 'https://schema.org',
		'@graph': [
			{
				'@type': ['WebPage', 'FAQPage'],
				'@id': `${page.url}#webpage`,
				url: page.url,
				name: page.title,
				description: page.description,
				isPartOf: { '@id': `${SITE}/#website` },
				about: { '@id': `${SITE}/#app` },
				breadcrumb: { '@id': `${page.url}#breadcrumb` },
				inLanguage: 'en',
				...modifiedFields(page.url),
				mainEntity: faqs.map((f) => ({
					'@type': 'Question',
					name: f.q,
					acceptedAnswer: { '@type': 'Answer', text: f.a }
				}))
			},
			{
				'@type': 'BreadcrumbList',
				'@id': `${page.url}#breadcrumb`,
				itemListElement: [
					{ '@type': 'ListItem', position: 1, name: 'Logic Nodes', item: `${SITE}/` },
					{ '@type': 'ListItem', position: 2, name: 'Truth table generator' }
				]
			},
			{
				'@type': 'SoftwareApplication',
				'@id': `${SITE}/#app`,
				name: 'Logic Nodes',
				url: `${SITE}/`,
				applicationCategory: 'EducationalApplication',
				operatingSystem: 'Web browser',
				isAccessibleForFree: true,
				offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' },
				author: { '@id': 'https://kriyak.com/#person' }
			}
		]
	})}${'<'}/script>`;
</script>

<svelte:head>
	<title>{page.title}</title>
	<meta name="description" content={page.description} />
	<link rel="canonical" href={page.url} />
	<meta name="author" content="Sem" />
	<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1" />
	<meta property="og:type" content="website" />
	<meta property="og:site_name" content="Logic Nodes" />
	<meta property="og:locale" content="en" />
	<meta property="og:title" content={page.title} />
	<meta property="og:description" content={page.description} />
	<meta property="og:url" content={page.url} />
	<meta property="og:image" content={page.image} />
	<meta property="og:image:alt" content={page.imageAlt} />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content={page.title} />
	<meta name="twitter:description" content={page.description} />
	<meta name="twitter:image" content={page.image} />
	{@html jsonLd}
</svelte:head>

<ContentPage
	related={[
		{ href: '/boolean-algebra-calculator', label: 'Boolean algebra calculator' },
		{ href: '/karnaugh-map-solver', label: 'Karnaugh map solver' },
		{ href: '/logic-circuit-generator', label: 'Circuit diagram generator' },
		{ href: '/logic-gates', label: 'The six logic gates' },
		{ href: '/learn', label: 'Learn digital logic' }
	]}
>
	<section class="intro">
		<h1>Truth table generator</h1>
		<p class="lede">
			Write a boolean expression in whatever notation you use, and get the full truth table as you type. Nothing is sent
			anywhere: it is all worked out in your browser.
		</p>

		<div class="card tool">
			<label class="field" for="expression">Boolean expression</label>
			<input
				id="expression"
				class="expression-input"
				type="text"
				bind:value={expression}
				spellcheck="false"
				autocomplete="off"
				autocapitalize="off"
				aria-describedby="expression-help"
			/>
			<p class="field-help" id="expression-help">
				<span class="mono">&amp; · ∧ and</span> for AND,
				<span class="mono">| + ∨ or</span> for OR,
				<span class="mono">! ~ ¬ ′ not</span> for NOT,
				<span class="mono">^ ⊻ xor</span> for XOR. Adjacent letters like
				<span class="mono">ab</span> mean a AND b. For several outputs, separate the expressions with
				<span class="mono">;</span> and name them: <span class="mono">sum = a ^ b; carry = a &amp; b</span>.
			</p>

			<div class="chips">
				{#each examples as example}
					<button type="button" class="chip-btn" on:click={() => (expression = example.value)}>
						{example.label}
					</button>
				{/each}
			</div>

			{#if error}
				<p class="error" role="status">{error}</p>
			{:else if table}
				<p class="reading" role="status">
					Reading it as <span class="mono">{reading}</span>
					{#if table.variables.length}
						over {table.variables.length}
						{table.variables.length === 1 ? 'variable' : 'variables'}
					{/if}
				</p>
				<div class="table-scroll">
					<table class="data-table result">
						<thead>
							<tr>
								{#each table.variables as variable}
									<th scope="col" class="mono">{variable}</th>
								{/each}
								{#each table.outputs as output}
									<th scope="col" class="mono out">{output.name}</th>
								{/each}
							</tr>
						</thead>
						<tbody>
							{#each table.outputs[0].rows as _, row}
								<tr class:high={table.outputs.every((o) => o.rows[row])}>
									{#each table.variables as _, bit}
										{@const on = !!(row & (1 << (table.variables.length - 1 - bit)))}
										<td class={on ? 'bit-1' : 'bit-0'}>{on ? 1 : 0}</td>
									{/each}
									{#each table.outputs as output}
										{@const value = output.rows[row]}
										<td class="out {value ? 'bit-1' : 'bit-0'}">{value ? 1 : 0}</td>
									{/each}
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
				<div class="export">
					<div class="opt" role="group" aria-label="Colours">
						<span class="opt-label">Colours</span>
						<button
							type="button"
							class:active={palette === 'colour'}
							aria-pressed={palette === 'colour'}
							on:click={() => (palette = 'colour')}>Colour</button
						>
						<button
							type="button"
							class:active={palette === 'mono'}
							aria-pressed={palette === 'mono'}
							on:click={() => (palette = 'mono')}>Black &amp; white</button
						>
					</div>
					<ShareLink what="the expression" />
					<div class="opt downloads">
						<button type="button" class="download" on:click={() => exportFile('svg')} disabled={exporting !== ''}>
							{exporting === 'svg' ? 'Saving…' : 'Download SVG'}
						</button>
						<button type="button" class="download" on:click={() => exportFile('png')} disabled={exporting !== ''}>
							{exporting === 'png' ? 'Saving…' : 'Download PNG'}
						</button>
					</div>
				</div>

				{#if sops.length === 1}
					<p class="summary">
						True in {sops[0].high} of {table.outputs[0].rows.length} rows. As a simplified sum of products:
						<span class="mono">{sops[0].text}</span>
						&nbsp;<a href={toolLink('/boolean-algebra-calculator', { expr: expression })}>simplify this further</a>
					</p>
				{:else}
					<p class="summary">
						Each output as a simplified sum of products:
						{#each sops as sop, i}
							<span class="mono">{sop.name} = {sop.text}</span>{i < sops.length - 1 ? '; ' : ''}
						{/each}
						&nbsp;<a href={toolLink('/logic-circuit-generator', { expr: expression })}>draw the circuit</a>
					</p>
				{/if}
			{/if}
		</div>
	</section>

	<section>
		<h2>Truth tables of the six basic gates</h2>
		<p class="section-intro">
			Every digital circuit is built from these. The rows count up in binary, the same as the table above.
		</p>
		<div class="gate-grid">
			{#each gateRef as gate}
				<div class="card gate">
					<h3>{gate.name}<span class="gate-symbol mono">{gate.symbol}</span></h3>
					<table class="data-table small">
						<thead>
							<tr>
								{#each gate.table.variables as variable}
									<th scope="col" class="mono">{variable}</th>
								{/each}
								<th scope="col" class="mono">Q</th>
							</tr>
						</thead>
						<tbody>
							{#each gate.table.rows as value, row}
								<tr>
									{#each gate.table.variables as _, bit}
										{@const on = !!(row & (1 << (gate.table.variables.length - 1 - bit)))}
										<td class={on ? 'bit-1' : 'bit-0'}>{on ? 1 : 0}</td>
									{/each}
									<td class={value ? 'bit-1' : 'bit-0'}>{value ? 1 : 0}</td>
								</tr>
							{/each}
						</tbody>
					</table>
					<p class="gate-note">{gate.note}</p>
				</div>
			{/each}
		</div>
		<p class="reducer">
			AND, OR, NAND and NOR are not limited to two inputs in
			<a href="/simulator">the simulator</a> — give them as many as the circuit needs.
		</p>
	</section>

	<section>
		<h2>A worked example: the half adder</h2>
		<p class="section-intro">
			A circuit can have more than one output, and then it has one column per output. Adding two single bits gives a sum
			and a carry — the sum is XOR, the carry is AND. That is the whole half adder.
		</p>
		<table class="data-table">
			<thead>
				<tr>
					<th scope="col" class="mono">a</th>
					<th scope="col" class="mono">b</th>
					<th scope="col" class="mono">sum</th>
					<th scope="col" class="mono">carry</th>
				</tr>
			</thead>
			<tbody>
				{#each halfAdder.sum.rows as sumValue, row}
					<tr>
						<td class={row & 2 ? 'bit-1' : 'bit-0'}>{row & 2 ? 1 : 0}</td>
						<td class={row & 1 ? 'bit-1' : 'bit-0'}>{row & 1 ? 1 : 0}</td>
						<td class={sumValue ? 'bit-1' : 'bit-0'}>{sumValue ? 1 : 0}</td>
						<td class={halfAdder.carry.rows[row] ? 'bit-1' : 'bit-0'}>
							{halfAdder.carry.rows[row] ? 1 : 0}
						</td>
					</tr>
				{/each}
			</tbody>
		</table>
		<p class="reducer">
			Read the last row: 1 + 1 is 0 carry 1, which is binary for 2. The generator above takes both outputs at once:
			<a href={toolLink('/truth-table-generator', { expr: halfAdderExpression })}>open the half adder as one table</a>
			or <a href={toolLink('/logic-circuit-generator', { expr: halfAdderExpression })}>draw it as one circuit</a>. Chain
			two half adders, then OR their two carry outputs together, and you have a full adder; chain four of those and you
			can <a href="/simulator#example:Calculator">add two four bit numbers</a>.
		</p>
	</section>

	<section>
		<h2>From a circuit, not an expression</h2>
		<p class="section-intro">
			The generator above starts from algebra. Logic Nodes goes the other way as well: build the circuit from real gates
			and it works out the table for you.
		</p>
		<ol class="steps">
			<li>
				<a href="/simulator">Open the simulator</a> and place an <em>Input</em> node for each variable and an
				<em>Output</em> node for each result, with your gates in between.
			</li>
			<li>
				Choose <strong>Build truth table</strong> from the toolbar. Every combination of inputs is evaluated and printed,
				including circuits with several outputs.
			</li>
			<li>
				To go backwards, start on an empty canvas and press <kbd>ctrl</kbd>+<kbd>T</kbd>. Fill in the outputs you want
				and the simulator builds a matching circuit out of gates.
			</li>
		</ol>
		<p>
			<a class="cta" href="/simulator">Open the simulator</a>
		</p>
	</section>

	<section class="faq">
		<h2>Questions</h2>
		{#each faqs as faq, i}
			<details open={i === 0}>
				<summary>{faq.q}</summary>
				<p>{faq.a}</p>
			</details>
		{/each}
	</section>
</ContentPage>

<style>
	.intro {
		padding-top: 64px;
	}

	.tool {
		padding: 1.1rem 1.2rem 1.3rem;
		margin-bottom: 1rem;
	}

	.field {
		display: block;
		font-size: 0.85rem;
		color: #ddd;
		margin-bottom: 0.35rem;
	}

	.expression-input {
		width: 100%;
		box-sizing: border-box;
		background-color: #0d0d0f;
		border: 1px solid rgba(255, 255, 255, 0.4);
		border-radius: 3px;
		color: #fff;
		font: 1.15rem ui-monospace, SFMono-Regular, Menlo, monospace;
		padding: 0.6rem 0.7rem;
	}

	.expression-input:focus {
		outline: none;
		border-color: #5db65d;
	}

	.field-help {
		color: #888;
		font-size: 0.8rem;
		margin: 0.45rem 0 0.7rem;
	}

	.chips {
		display: flex;
		flex-wrap: wrap;
		gap: 6px;
		margin-bottom: 1rem;
	}

	.chip-btn {
		background: #0d0d0f;
		border: 1px solid rgba(255, 255, 255, 0.4);
		border-radius: 3px;
		color: #ddd;
		font-size: 0.8rem;
		padding: 0.25rem 0.6rem;
		cursor: pointer;
	}

	.chip-btn:hover {
		border-color: #5db65d;
		color: #fff;
	}

	.error {
		color: #f66;
		font-size: 0.9rem;
		margin: 0.5rem 0 0;
	}

	.reading {
		color: #bbb;
		font-size: 0.9rem;
		margin: 0 0 0.7rem;
	}

	.table-scroll {
		overflow-x: auto;
		max-height: 420px;
		overflow-y: auto;
		border-radius: 3px;
	}

	/* A truth table reads better compact than stretched across the card. */
	.result {
		width: auto;
		min-width: min(100%, 24rem);
	}

	.result th,
	.result td {
		text-align: center;
		padding-left: 1.1rem;
		padding-right: 1.1rem;
	}

	/* :global so the rule survives scoping (Svelte omits the class on <thead>),
	   which is what actually makes the header stick on long tables. */
	.result :global(thead th) {
		position: sticky;
		top: 0;
		background-color: #101012;
	}

	.result tr.high td {
		background-color: rgba(51, 119, 34, 0.16);
	}

	.result .out {
		border-left: 1px solid rgba(255, 255, 255, 0.25);
	}

	.export {
		display: flex;
		align-items: center;
		gap: 1.1rem;
		flex-wrap: wrap;
		margin-top: 0.9rem;
		padding-top: 0.9rem;
		border-top: 1px solid rgba(255, 255, 255, 0.15);
	}

	.opt {
		display: inline-flex;
		align-items: center;
		gap: 4px;
	}

	.opt-label {
		color: #888;
		font-size: 0.75rem;
		text-transform: uppercase;
		letter-spacing: 0.04em;
		margin-right: 0.15rem;
	}

	.opt button {
		background: #0d0d0f;
		border: 1px solid rgba(255, 255, 255, 0.4);
		border-radius: 3px;
		color: #ddd;
		font-size: 0.8rem;
		padding: 0.3rem 0.7rem;
		cursor: pointer;
		white-space: nowrap;
	}

	.opt button.active {
		background-color: #372;
		border-color: #5db65d;
		color: #fff;
	}

	.downloads {
		margin-left: auto;
	}

	.download {
		border-color: #5db65d !important;
		color: #8ede8e !important;
	}

	.download:disabled {
		opacity: 0.5;
		cursor: default;
	}

	.summary {
		color: #bbb;
		font-size: 0.88rem;
		margin: 0.8rem 0 0;
	}

	.gate-grid {
		display: grid;
		grid-template-columns: repeat(auto-fit, minmax(230px, 1fr));
		gap: 12px;
	}

	.gate {
		padding: 0.9rem 1rem 1rem;
	}

	.gate h3 {
		display: flex;
		align-items: baseline;
		justify-content: space-between;
		gap: 0.5rem;
		color: #fff;
	}

	.gate-symbol {
		font-size: 0.85rem;
		color: #999;
	}

	.gate .small {
		width: 100%;
		font-size: 0.85rem;
	}

	.gate-note {
		color: #888;
		font-size: 0.8rem;
		margin: 0.6rem 0 0;
	}

	.steps {
		padding-left: 1.25rem;
		color: #ddd;
		max-width: 660px;
	}

	.steps li {
		margin-bottom: 0.8rem;
	}
</style>
